### ISSUE TITLE
Notes  from meeting of 4/9/19

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#1]
# New London curriculum

Present: Michael, Aisha, Oliver, Kristina, Dan

4/9/19 TO DO
- go through existing curriculum and add bullet points to the list below

### Overall approach
1. learning outcomes will describe testable functionality
1. code reviewers will test for those learning outcomes
1. if a learning outcome is not introduced in an associated workshop, then it will be a spike/research topic

----

1. Concept: static website
   PROJECT: 
    - semantic HTML
    - accessibitility
    - performance
    - git/git workflow

    Tools
    - debug CSS
    JS
    - dom manipulation
    CSS
    - responsiveness (mobile/desktop)
    - transitions
    - flexbox (navbar)
    testing
    - manual QA

2. Concept: HTTP
   PROJECT: 
    - req/resp
    - fetch
    - 
    Tools
    - debugging js
    - (chrome) network tab
    - postman
    JS
    - array methods
    CSS
    - grid (render a grid of data)
    testing
    - make DOM tests pass

EXTRA: FAC api for Weeks 2+3

3. Concept: build systems
   PROJECT: 
    - npm
    - automated testing

    - searchable api / form
    - error handling

    Tools
    - linting
    - prettier?

    JS
    - object manipulation
    - client-side validation
    CSS
    - client-side validation
    testing
    - automated unit tests?

4. Concept: node 
   PROJECT: vanilla HTML form
    - vanilla server
    - buffers/streams
    - core node modules
    - CommonJS modules system
    - forms/posting/redirecting

    Tools
    - debugging server
    - nodemon
    JS
        - error-first callbacks
    CSS
        - forms-more than just text input
    testing
        - server testing -> response?
        - TDD with supertest

5. Concept: Databases
   PROJECT: 
    - schema design
    - SQL
    - db setup/management

    Tools
    - psql
    - environments
    JS
    - abstraction
    CSS
    - 
    testing
    - db testing

6. Concept: Auth
   PROJECT: 
    - hashing/salting
    - jwt
    - sessions/cookies
    - bcrypt
    - ssl
    - stateless vs stateful sessions

    Tools
    - application tab (chrome)
    - CI (GitHub actions or travis)
    JS
    - promises (roll your own)
    - 
    CSS
    - logging-in UX
    testing
    - 

7. Concept: Express 
   PROJECT: User profile?
    - templating
    - design patterns (MVC)
    - REST APIs
    - middleware (as a concept)

    Tools
    - more postman
    JS
    - template literals
    CSS
    - a CSS preprocessor?
    testing
    - mocking

8. Concept: Full-stack app
   PROJECT: 
    - full stack error handling
    - handlers
    - build steps

    Tools
    - 
    JS
    - throwing and catching errors
    CSS
    - 
    testing
    - 

----

### WEEKS 10-16 (FOR LATER)

Possible learning outcomes:
- Build a PWA with service workers and localstorage
- Using D3 for Data visualisation
- Deploy on Netflify (and possibly AWS)

### Student project

    UI/UX
    - 
    DevOps
    -
    QA
    - 
    Scrum
    - 

### Tech for Better project

    UI/UX
    - 
    DevOps
    -
    QA
    - 
    Scrum
    -

**Comment by oliverjam** [comment]
Here are all the original whiteboard notes (they probably match what you've typed out, but just for the record)

![1](https://user-images.githubusercontent.com/9408641/69626750-3406c900-1041-11ea-8c50-130fa7300501.jpg)
![2](https://user-images.githubusercontent.com/9408641/69626751-349f5f80-1041-11ea-80af-ef242bade5f5.jpg)
![3](https://user-images.githubusercontent.com/9408641/69626752-349f5f80-1041-11ea-86f3-8a68546ec703.jpg)
![4](https://user-images.githubusercontent.com/9408641/69626754-349f5f80-1041-11ea-960b-6222a39de4be.jpg)
![5](https://user-images.githubusercontent.com/9408641/69626755-3537f600-1041-11ea-954d-9ee0085168ee.jpg)
![6](https://user-images.githubusercontent.com/9408641/69626757-3537f600-1041-11ea-8e0d-eb450b4e7c49.jpg)
![7](https://user-images.githubusercontent.com/9408641/69626758-35d08c80-1041-11ea-93ed-e62b4ffbbd12.jpg)
![8](https://user-images.githubusercontent.com/9408641/69626759-35d08c80-1041-11ea-83f0-4fa43da0017d.jpg)
