### ISSUE TITLE
Installation guidance for course participants

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#103]
Given the problems that some students on FAC19 are having with installing, in particular PostgreSQL, on Windows, we may want to update or make clearer our guidance and move it here. See [precourse installation list](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/precourse/README.md#installation-list).

**Comment by oliverjam** [comment]
Pretty sure we covered this in #160 

Also I think Elias made some updates to the [Postgres installation guide repo](https://github.com/coding-wiki/learn-sql/blob/master/postgresql/setup.md) after FAC19 had problems.
