### ISSUE TITLE
Outline employment curriculum

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#109]
A rough outline for an employment curriculum for our Tuesday afternoon slot:
- Week 1 - GitHub
- Week 2 - Twitter
- Week 3 - LinkedIn
- Week 4 - a website on netlify + a vanity domain
- Week 5 - favicons + personal branding
- Week 6 - portfolio site examples
- Week 7 - CVs + examples
- Weeks 8 and beyond - design bursts and peer review

Each week, we would expect to:
- define a short series of tasks to complete;
- create a short tip sheet of best practice
- create or point to some relevant resources.

For FAC19, we have initiated a different schedule, but we can use this as a reference and backfill the topics we haven't covered yet as we go.

**Comment by sofer** [comment]
From Week 11, I suggest that Wednesday afternoons 2-5pm be set aside for employment preparation.

**Comment by sofer** [comment]
Interview practice:
- https://www.pramp.com/
- https://leetcode.com/ (or https://www.hackerrank.com/)

**Comment by oliverjam** [comment]
### Circle discussion

React Week probably can't fit a 3 hour slot. Design Week can spare an hour on Wednesday.

From Week 12 we'll use all of Wednesday afternoon for employment prep.

**Comment by sofer** [comment]
- Week 10: 30-min intro to pramp + scheduling of sessions for Week 11
- Week 11: 1-hour remote interview prep on pramp
- Week 12+ 3 hour sessions

@sofer to run.

**Comment by sofer** [comment]
@helenzhou6's slides https://hackmd.io/@uYhtwaTkQeyelbBdX4OTeA/Sk0ek1Xq8#/ ❤️

**Comment by sofer** [comment]
@sofer to plan Week 12 campaign before next week!

**Comment by sofer** [comment]
We possibly do need to get everyone on twitter, too. I'll add something about it as part of the campaign session.

**Comment by sofer** [comment]
Deck for tomorrow: https://hackmd.io/@sofer/Byy4rXbiI#/

Notes to self:
- https://javascript.info/
- https://1loc.dev/

**Comment by sofer** [comment]
Just to report that yesterday's session went very well and they now pretty much have their work cut out and a clear plan of action for the next month. They will be reporting back each Wednesday. I'll probably aim to add a short specific topic each week in response to requests. Next week I'll talk about in-house graduate opportunities--assuming the first of those come in by next week, but if something else comes up between now and then, I'll attempt to respond to it.

**Comment by sofer** [comment]
Reminder  to self: talk about how to talk about FAC with employers in Week 14:
- partnerships
- apprenticeships
- week of mentoring
- "pay what you can"

**Comment by sofer** [comment]
Slide deck for Wed: https://hackmd.io/@sofer/HJ9SABGhL#/

**Comment by sofer** [comment]
Suggestion: get volunteers for mentoring employment prep.

**Comment by sofer** [comment]
FAC20 employment prep: 

Groups of 4 based on Week 11-13 project groups. 

For each session, split the sessions into two parts:
1. Review the work from the previous week in pairs  
2. New task: work on it independently (or in pairs)

Topics:
- LinkedIn
- CV
- Portfolio website
- Job search
- Interviews

Prepare guidance and templates for each topic in advance.

For reviews:
- Pair up
- Take 5 mins to review each others' work
- Each take 5 mins to give feedback
- Repeat twice, so that everyone in the group reviews each others' work 
- ~45 minutes

For job search, the task can be to ask students to spend some time finding jobs for each other.
For LinkedIn ensure everyone endorses each other for the appropriate skills and every group member leaves nice reviews for each other (3 in total).

Finish off with pramp.

So, the schedule is possibly as follows:

- Week 11: LinkedIn profile
- Week 12: LinkedIn review; CV writing
- Week 13: CV review; Portfolio website (first draft)
- Week 14: Website review; job search
- Week 15: Practice interviews
- Week 16: pramp.com

**Comment by oliverjam** [comment]
Are we not still planning on running this during the first half of the course?

**Comment by sofer** [comment]
@jackherizsmith and @sofer to liaise on this issue and #191

**Comment by jackherizsmith** [comment]
@jackherizsmith to find time to meet with @sofer and discuss an optimal transition from design bursts to employment prep

**Comment by sofer** [comment]
FAC19 feedback: CV reviews from alumni would also be useful.

**Comment by jackherizsmith** [comment]
@sofer 

Assuming employment prep starts in week 4 when design bursts end, how much of Wednesday afternoons (currently projects) would you like to use? It is scheduled in the default schedule to start at 3.30, which gives 90 minutes to finish the day's project prep / initial stages, and 2 hours for employment (later incl community engagement).

With 4 sessions before reading week, perhaps:

Week 4 - GitHub
Week 5 - Twitter & LinkedIn
Week 6 - a website on Netlify & a vanity domain (good timing I think!)
Week 7 - favicons, personal branding & portfolio site examples
READING WEEK - time for designing / building portfolio sites, CV examples
Weeks 8 and beyond - design bursts and peer review

I'm not sure on what the teams could be. On the one hand I liked having the same team each week, but that is because they were the best people and there wasn't any cross-pollenation of ideas. It's also how to make cliques happen I guess. If we do go for one employment team throughout, this could be the week one team.

**Comment by jackherizsmith** [comment]
I would also like to discuss and introduce employment mentors, which I will raise as a new issue

**Comment by jackherizsmith** [comment]
Add 'make a GitHub profile readme' to week 4 GitHub week
https://www.aboutmonica.com/blog/how-to-create-a-github-profile-readme

**Comment by sofer** [comment]
@jackherizsmith to lead, but supported by @sofer and Jack's first task is schedule a meeting between the two of us.

**Comment by jackherizsmith** [comment]
https://hackmd.io/jY8pyE7iTWaThtkuUNgSjw - Employment intro

**Comment by sofer** [comment]
Employment prep, 2nd Week (i.e. Week 5) : https://hackmd.io/@sofer/BJ0aPm4Zw#/

**Comment by jackherizsmith** [comment]
_In pairs from previous project teams_

**Week 4** GitHub
**Week 5** Twitter
**Week 6** LinkedIn
**Week 7** Employment mentor planning
**Reading week** Employment mentor intro
**Week 9** Portfolio site

_With week 1 project team_

**Week 10** CV
**Week 11** Cover letter
**Week 12** Job boards
**Week 13** Recruiters (talent.io, Hired)
**Week 14** CV & cover letter review
**Week 15** Applications
**Week 16** Applications
**Week 17** Tech tests
**Week 18** Interview prep

**Comment by jackherizsmith** [comment]
@jackherizsmith to link these
