### ISSUE TITLE
Splitting into two groups for workshop presentations

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#114]
Another upshot of this morning's conversation with @oliverjam and @yvonne-liu.

Might it be worth splitting up into two groups for workshop solution presentations once the workshops are all written and people are familiar with them. Perhaps we could trial this approach with React week, which is going to be largely unchanged from previous cohorts?

**Comment by sofer** [comment]
This was specifically asked for in SGC this afternoon. There was a roughly two thirds majority in favour. @oliverjam responded by saying he would talk to the mentors about it for Week 8, next week.

**Comment by sofer** [comment]
If FAC19 believe that this has been successful, it might be worth considering splitting up into two groups for presentation Q&A, too.

**Comment by oliverjam** [comment]
I would say it's been successful for the longer workshops. I'm not sure there are enough questions or confusion/things to be explained after presentations for the benefits to outweigh the inconvenience there though.

**Comment by sofer** [comment]
> I would say it's been successful for the longer workshops.

@oliverjam is the rule of thumb we can use for which workshops would benefit from being split up?

**Comment by oliverjam** [comment]
### Circle discussion

- We should formalise the structure of our workshops.
- If we decide to make changes like this it can be documented rather than relying on mentors remembering
- @oliverjam to write this for the Coursebook
- Splitting into two should be the default for remote workshops, but this is both more difficult and less necessary in person

**Comment by oliverjam** [comment]
Closing in favour of #142
