### ISSUE TITLE
Add SQL resources to pre-course

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#116]
It's a bit much to expect students to learn all of SQL in one morning whilst also learning databases. It might be a good idea to include a short (<4 hour) introductory resource (like Codecademy's one) so students get a taste for it in advance.

**Comment by Albadylic** [comment]
Relates #115

**Comment by Albadylic** [comment]
Have been working through CodeAcademy's intro today - linked above. It's a good entry level and explains well. I think having the minimum requirement as completing the first section and maybe the second too.

First introduces Selectors, constraints, creating tables.
Second introduces operators, etc.

It took me about 40 minutes to do the first one, the second I'm about halfway through (20 mins). I think we could assign the whole thing as 4 hours or the first 2 (of 4) for 2 hours.

**Comment by oliverjam** [comment]
Yeah i think there are 2 separate concerns: ensuring postgres is installed correctly and giving them some entry level SQL experience.

I can create a small command-line-only challenge where they have to run some SQL to initialise a table, then select some data from the table. This would hopefully surface any installation issues

**Comment by oliverjam** [comment]
The Codecademy stuff sounds great though. I don't think 4 hours is too much time to add to the precourse
