### ISSUE TITLE
New pre-course

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#118]
Including:
- [ ] #115 
- [ ] #116 

And possibly introduce it earlier.

**Comment by oliverjam** [comment]
@oliverjam to create an small introductory SQL workshop that ensures students have Postgres installed correctly

**Comment by sofer** [comment]
Move Precourse into the coursebook. @Albadylic to look at #115 tomorrow and raise a pr. @oliverjam to look at #116 this afternoon.

**Comment by sofer** [comment]
All done, I think. Closing now.
