### ISSUE TITLE
When to change groups 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#119]
- Week 1
- Weeks 2-3
- Week 4 
- Weeks 5-6
- Weeks 7-8

It was probably a tactical error changing after Week 5 for FAC19.

**Comment by Albadylic** [comment]
And update the LP/Teams.md so that the table has names rather than letters related to a key

**Comment by Albadylic** [comment]
Resolved here: https://github.com/fac20/cohort/pull/1
