### ISSUE TITLE
Reading week

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#120]
Add guidance for Reading Week to the course book ~~for Week 9~~

**Comment by sofer** [comment]
- Portfolio site
- Review of coursebook
- Additional reading

**Comment by sofer** [comment]
https://www.pramp.com/, perhaps.

**Comment by oliverjam** [comment]
This is the guidance I gave to FAC19 (in their "study group" channel so as not to pressure people taking a week off)

> ### Frontend Challenges
> These are mostly HTML/CSS. Good to brush up on creating properly nice looking frontend things
https://piccalil.li/category/front-end%20challenges%20club/
>
> ### JavaScript 30
> This is a little old now (I did some of these while applying for FAC :scream:) but they’re still super relevant.
> Great for brushing up on JS/DOM basics whilst building some interesting small things. I’d scan the list of projects and pick a couple that sound interesting to you.
https://javascript30.com/ (edited) 
>
> I’d also recommend revisiting any of the Spikes topics you didn’t do and reading the resources for it. They’re generally a pretty good overview of an interesting subject.

**Comment by oliverjam** [comment]
### Circle discussion

Reading Week shouldn't have much "work" recommended (especially portfolio sites). We should just have resources for them to read/revise.

Can point them to the existing further reading for each week (and spike topic resources).

**Comment by jackherizsmith** [comment]
- add section to gitbook with a page for guidance and some things to do / consider (e.g. revisit spikes)

**Comment by jackherizsmith** [comment]
- or, call that section "Extracurricular learning" and include guidance for both term time and reading week as separate pages.

**Comment by jackherizsmith** [comment]
@jackherizsmith to add existing material to Gitbook

**Comment by Albadylic** [comment]
[This](https://hackmd.io/@3h2qEDKEQXSZK4l2wloSMg/SJrDiJyBB) is the checklist we used to share - may be a helpful starting point
