### ISSUE TITLE
Mentor guidance for the second half of the course

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#122]
In particular, we want a project reviewer who could do some live refactoring of project code in each of the one-week build sprints.

Also, all four role mentors.

**Comment by sofer** [comment]
[What's the script?](https://github.com/foundersandcoders/london-programme/issues/1025) is a good starting point. Perhaps we can just move that guidance into the coursebook.

**Comment by sofer** [comment]
In particular, we need pretty good guidance for any mentors doing refactoring. @oliverjam has offered to review the first draft.

**Comment by oliverjam** [comment]
### Circle discussion

Create a `projects` (or something) folder in the Coursebook with second half of the course guidance.

**Comment by sofer** [comment]
@Albadylic to make a pr in this repo for the [mentor guidance](https://github.com/foundersandcoders/london-programme/issues/1025#issuecomment-620511704).

**Comment by sofer** [comment]
@Albadylic to look at this tomorrow and post pr.
