### ISSUE TITLE
Internal links are broken in documents/retrospectives.md

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#125]

**Comment by oliverjam** [comment]
Which links are broken? this is probably because there were relative links inside `master-reference`, where this used to live. They must have not gotten updated when we copied the markdown across

**Comment by Albadylic** [comment]
Seems to be the ones linked from "London, Nazereth, Gaza" which link to outdated repos (e.g. foundersandcoders/london-curriculum). and also "student teams" which should link to london-programme/[cohort]/teams.md

Given that the coursebook should now serve as central curriculum document and that the teams link will change per cohort: I'd suggest removing these links altogether.

Happy to be assigned to reviewing this document.
