### ISSUE TITLE
Move workshops inside the foundersandcoders organisation

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#129]
Unless we don't feel the need to?

We'll need to update all the links in the coursebook, too.

And apply the appropriate open source licence.

**Comment by sofer** [comment]
Provisionally decided to move workshops and the coursebook into a new organisation. Name to be confirmed.

**Comment by sofer** [comment]
I have added the next-circle label, given recent discussions about sharing the curriculum with applicants and giving clear guidance about the use of this curriculum by others.

**Comment by oliverjam** [comment]
I wonder if the GitHub API has a way to move repos. Otherwise this might take a while 😅

**Comment by sofer** [comment]
We may move these into the foundersandcoders org after all, but it needs a big clear out before we decide one way or the other.

**Comment by sofer** [comment]
Changed our minds again. I have created a separate org. https://github.com/fac-curriculum.

However, @oliverjam @Albadylic this is a bit of a mouthful, how about https://github.com/fac-torials ?

Like a tutorial, but it's facilitated, so it's a "factorial" :-)

**Comment by oliverjam** [comment]
Good pun, but I think the name should be as obvious as possible. Even `master-reference` is a bit confusing

**Comment by sofer** [comment]
https://github.com/fac-book

**Comment by sofer** [comment]
Agreed with fac-book for now. Green light for Oli to start moving material into the new org.

**Comment by sofer** [comment]
@oliverjam to schedule before net circle a date (half day) in advance to do this.

**Comment by oliverjam** [comment]
@oliverjam to do this in Reading Week so we don't disrupt anything

**Comment by sofer** [comment]
@oliverjam will close once it's been done.

**Comment by oliverjam** [comment]
This is actually superseded by #297, since workshops aren't going to be separate repos anymore
