### ISSUE TITLE
Course week naming

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#131]
For the purposes of the coursebook, it might be unhelpful to treat *Reading Week* as a separate week. Effectively the course is made up of a 9-week core curriculum followed by project work. See also https://github.com/foundersandcoders/hq/issues/491.

**Comment by oliverjam** [comment]
Yeah we can rename Week 10 to Week 9 before FAC20

**Comment by oliverjam** [comment]
Closing in favour of #137
