### ISSUE TITLE
SPA week revisions

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#132]
I'm not sure that Week 8 was very well focused. I didn't know exactly what I wanted to teach (other than "frontend"). The workshops were generally a bit long and confusing (nobody finished any) so I think the week would benefit from the stripped down focused tasks.

Part of this was the time pressure: it's easier to write a long tutorial style workshop than it is a few smaller challenges. I look forward to the cohort's feedback tomorrow, then I'll have a think about possible changes.

**Comment by oliverjam** [comment]
@oliverjam to furiously work on some new workshops for next week. Here's a rough plan:

1. Remove client-side routing workshop
   This is long and confusing, especially for people who have never heard of this concept before. Also building an entire routing library is overkill, and it taints the rest of the week as you have to understand this workshop to follow the subsequent ones that make use of it.
1. Add reactive rendering workshop
   Something like [this](https://codepen.io/oliverjam/pen/rNeGyEP) where updating state triggers a re-render. The idea is to work towards a naive React-like rendering setup and think about structuring your frontend more rigorously ("components" as functions that return DOM elements etc).
1. Extract token-based authentication stuff from SPA workshop
   This will be necessary for working with the API they built in the previous week. Most people won't have used localStorage etc before. Since this is part of an existing workshop it won't be much work.
1. Either something on building a better `fetch` abstraction that handles errors etc, or something on testing frontend components.

**Comment by jackherizsmith** [comment]
Hugely successful 

https://founders-and-coders.gitbook.io/coursebook/curriculum/single-page-app/schedule
