### ISSUE TITLE
Presentation Timings

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#133]
For FAC 20, we should have clear timings for spike and project presentations. My suggestions are:

8 minutes on Tuesday for Spikes
12 minutes on Friday for Projects
With an additional (up to) 5 for questions. 

This gives us room for presentation prep on Tuesday (10 mins at 10:00) & a break before SGC on Friday (commencing at 15:10). I believe that giving specific timings (8 rather than 10) will also increase consciousness of time.

**Comment by jackherizsmith** [comment]
How do we feel about being very strict with time? Calling it after exactly 8 minutes (allowing for technical issues).

**Comment by Albadylic** [comment]
I think that's a reasonable idea so long as people know prior to presenting. I'd say you can be lenient in the first few weeks, be stricter from around week 3 and ask students to time themselves from week 6

I found it hard to communicate timings over Zoom (in the classroom we usually used Hand signals or signs) and wondered if you had any thoughts on that?

**Comment by jackherizsmith** [comment]
Sorry I just saw this. I'm going to look into GitHub notifications so I don't miss them.

Can I send a broadcast message if there are no breakout rooms open? I'm trying the route of "timing is really important" and I think it helps that they don't have prior classroom experience of being a bit more free form. Running over by ten minutes on their first spike was pretty good tbh, although they only got one question each.

**Comment by oliverjam** [comment]
I don't think you can broadcast to the main room unfortunately

**Comment by jackherizsmith** [comment]
- [ ] update coursebook
