### ISSUE TITLE
React Week schedule

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#134]
Given the delays to Tech for Better and uncertainties around employment, we'd like to hold discussions with the cohort during React Week if we can find the time for this.

1.5 hours - Year Here Tech for Better session on Tuesday at 4:30pm.
0.5 hours - Employment prep/discussion - Wednesday at 11:00??
1 hour - Tech for Better project pre-selection discussion - on Friday between presentations & SGC
- Currently Friday presentations time is 120 mins (15 per team of two) - we could cut to 60 mins (7.5 per team of two)

1 hour - Code of Conduct Review - This may have to come the week after??

**Comment by Albadylic** [comment]
I think Bobby will be happy to do his talk during Design Week which would give us an extra hour for TFB pre-selection. We could do CoC review before SGC on Friday, if we're happy with shorter presentations.

**Comment by oliverjam** [comment]
Mon/Tue are very tight schedules already. Maybe we can discuss this in the Circle today
