### ISSUE TITLE
Update to Friday Schedule

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#135]
From experience with FAC19 - it might be good to update the Friday schedule to look like this:

14:00 - Presentations start :movie_camera:
15:10 - Break after Pressies :coffee: :cocktail:
15:30 - Cohort SGC ☝️ 👆 
16:15 - Team SGC  :smiley_cat:
17:00 - Friday Speaker :seedling:

Relates #133  - perhaps worth re-visiting #72 with this in mind.

**Comment by jackherizsmith** [comment]
@Albadylic are we good to close this?

**Comment by Albadylic** [comment]
Yep, closing now
