### ISSUE TITLE
Add more React example projects

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#136]
Pick a few good student projects

**Comment by Albadylic** [comment]
[FAC17 Project Gallery](https://fac-17.github.io/fac17-projects-gallery/)

[FAC18 Project Gallery](https://fac18.github.io/fac18-projects-gallery/)

**Comment by oliverjam** [comment]
@jackherizsmith to find a good inspirational FAC19 example to add to the React Week project intro

**Comment by jackherizsmith** [comment]
https://stoic-hoover-c4bfbc.netlify.app/ - Spotify recommendations
https://artattack.netlify.app/ - art attack
