### ISSUE TITLE
Make React Week week 9

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#137]

**Comment by sofer** [comment]
Another possibility: Bring Reading Week forward by a week to straight after Week 7 and have another break (or employment prep) after Week 13. @oliverjam to bring it to SGC and then talk about it in the general circle next week.

**Comment by oliverjam** [comment]
We have changed the schedule for FAC20:

- REST APIs
- Reading week
- Fullstack App
- React
