### ISSUE TITLE
Guidance on mentor volunteering

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#138]
Currently, mentor volunteering in the second half of the course is done on an ad hoc basis. Given how  important these roles are, it might make sense to offer guidance in the coursebook on how and when to go about appointment to these roles. As a starting point, how about the following:

1. Open up volunteering for React week as an option for recent graduates in Week 1 and then for more experienced alumni in Week 5;
2. Open up the project and role mentor roles for the student project to recent graduates in Week 1 and then to more experienced alumni in Week 5;
3. Open up the Tech for Better mentor roles to more experienced alumni in Week 5. 

This strikes a good balance between giving recent alumni an opportunity to extend their experience of mentoring while also giving an opportunity for students to get the benefit of more experienced mentors. It also makes it more likely that we will pin down the mentors well before they are needed.

**Comment by jackherizsmith** [comment]
Also creating mentoring guidance for FAC19 weeks 1-9

**Comment by sofer** [comment]
Let me amend this.
- I am no longer suggesting that less experienced alumni mentor in the second half of the programme.
- And guidance: https://github.com/foundersandcoders/coursebook/blob/master/projects/mentor-roles.md

We may be able to close this, as soon as we have guidance for the CF to select mentors (which we don't yet, I think).

**Comment by Albadylic** [comment]
@jackherizsmith and I have written up [this document](https://hackmd.io/@fac/BJMtefk-P) which summarises how the CF should select mentors. Will be merged into CF documentation when the time is right.
