### ISSUE TITLE
Estimation and issue management in Week 1

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#14]
Could we consider introducing the basic principles of estimation and issue management in Week 1?

## Terms
- Scrum(TM) - a widely-used software development method, that uses some of the terms below
- sprint - The fixed period of development time between planning and review
- velocity - the projected team capacity (expressed in points )for one sprint
- user story - an action that a user wants to perform
- estimate - how long you think a user story will take to develop
- points - the (somewhat arbitrary) unit of estimation
- chore - something you haven't done yet, but needs to be done, not directly related to a story
- bug - something broken
- feature - something that was not in the original spec
- refactor - an improvement to your existing code
- [project board](https://help.github.com/en/github/managing-your-work-on-github/about-project-boards) - which you are going to use to visually track your project

## Labels
To be added to GitHub issues
- E1 - Small story, estimated
- E2 - Medium story, estimated
- E3 - Actual story, estimated
- A1 - Small story, actual
- A2 - Medium story, actual
- A3 - Actual story, actual
- story, chore, bug, refactor, feature
- in progress, done (stretch: use triggers)

## The project
Provide 6 user stories, 2 points each. Velocity: 12 points 
- Stretch: Use the automatic triggers in the project board

Code review:
- incoming issues should be correctly labelled as chore, bug, refactor or feature

Presentation:
- show estimates vs actual points
- show issues correctly labelled
- show project board

**Comment by oliverjam** [comment]
I like the idea of this being covered more explicitly in the course. Two concerns:

1. Do we have time for this in week 1?
1. Will it be overwhelming to throw even more process overhead on them right at the start. (They already have to remember all the pairing and git/GitHub stuff, which is totally new)

**Comment by sofer** [comment]
Week 2, perhaps.

**Comment by sofer** [comment]
Will deliver a first version of this on Monday, Week 12

**Comment by sofer** [comment]
For delivery next week: https://hackmd.io/@sofer/r1qwe03RS#/

**Comment by bobbysebolao** [comment]
The talk on Tuesday was really good. I wonder if it might be worth adding a bit to the glossary section to explain the term 'technical spike', as not all of the fac18 students knew that term. Looking forward to see quick presentations of their kanban boards later this week!

**Comment by sofer** [comment]
@bobbysebolao added a definition of `spike` to the slides.

**Comment by sofer** [comment]
I think we are doing the spike! talk #64 on Tuesday afternoon. 
Perhaps we can do:
- Week 1, Wed 11:00 [A very short intro to project management](https://hackmd.io/@sofer/S1wGfV2M8#/)
- Week 2, Wed 11:00 [Issue management and estimation](https://hackmd.io/@sofer/B1AL4V3ML#/)

**Comment by oliverjam** [comment]
@sofer Are you happy with how this went? It seemed like the cohort ended up doing some decent project management each week

**Comment by sofer** [comment]
Yes, very happy, although I would have liked them to have kept up the reporting of estimates vs actual points. I just re-checked the slides and [added one](https://hackmd.io/@sofer/B1AL4V3ML#/2/9).

**Comment by sofer** [comment]
Moved the slides to the FAC account.
- [A very short intro to project management](https://hackmd.io/@fac/S1wGfV2M8#/)
- [Issue management and estimation](https://hackmd.io/@fac/B1AL4V3ML#/)

**Comment by sofer** [comment]
And made a pr for the new slide links.

**Comment by oliverjam** [comment]
Awesome, thank you
