### ISSUE TITLE
Resources for each week

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#143]
Optional extra reading for each week. Can also be used for Reading Week revision (see #120)

**Comment by jackherizsmith** [comment]
@oliverjam not sure if you were on zoom at the time but extra curricular reading came up following the cohort expectations. I can help compile a list for each week for curriculum mentors to circulate?

**Comment by oliverjam** [comment]
I wasn't on the Zoom. I've started compiling these, but got overwhelmed by how much stuff ended up in fac19/resources 😅

If you'd like to help that would be great. I know I posted useful things on Slack, just need to scroll back

**Comment by oliverjam** [comment]
I added resources for weeks 1-5 in this PR #211 

We need to get 6/7/8 done before Week 6 I guess
