### ISSUE TITLE
Intro presentations at the start of each week

### ISSUE THREAD

**Issue by bobbysebolao** [foundersandcoders/coursebook#15]
Based on feedback from past cohorts (and [this discussion](https://github.com/foundersandcoders/master-reference/issues/1057)), it would be a good idea to create a short intro presentation for each week's topic (where one doesn't already exist). 

I suggest we check these tick boxes as we add presentations for each week, and close the issue once every week has been covered:

- [ ] Week 1 presentation
- [ ] Week 2 presentation
- [ ] Week 3 presentation
- [ ] Week 4 presentation
- [ ] Week 5 presentation
- [ ] Week 6 presentation
- [ ] Week 7 presentation
- [ ] Week 8 presentation

Intro presentations that currently exist:
- [Intro to Express presentation](https://hackmd.io/treNCrYPTva8WyJXq-JZcg?both) (created by @reubengt )
- [Intro to password management presentation](https://drive.google.com/file/d/0BxXF_LZcFnS5ODM0dElWYmtmMWc/view)
- [Intro to databases presentation](https://docs.google.com/presentation/d/14LXEKmHM6xqjTvPLyKw0trtprGeNkD0VLgWkE8Z2ouo/edit?usp=sharing)

**Comment by oliverjam** [comment]
We did a presentation each week and it went pretty well 🎉
