### ISSUE TITLE
Design Week reflections: balance between UX and UI

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#152]
- we may have too much time on figma
- otoh having a detailed figma design may be useful for the build sprints
- we are in agreement that design week needs more thought.

Returning to this next week.

**Comment by Albadylic** [comment]
Some reflections from what we've heard today
- Decision making part of the process needs to be emphasised more
- User Testing should be conducted on Thursday Morning so the prototype can be adapted in the afternoon
- At least two hours for sprint planning

**Comment by sofer** [comment]
Agreed that the outcome of the week should not be so focused on producing a polished figma prototype. A rough and ready prototype is sufficient. Having more on user testing would make more sense. We need to schedule sufficient time to:
- contact users for scheduling testing in advance
- learning about scripting user testing sessions and screen recording
- actually doing the user testing
- feeding back on user testing

@Albadylic to add in a user testing session tomorrow for next week and then update the design week schedule.

**Comment by jackherizsmith** [comment]
Action: Jack to come up with Design Week timeline, speakers, mentors etc. Range of 'design' tasks (e.g. CI, deployment)

**Comment by Albadylic** [comment]
Relates to #183

**Comment by Albadylic** [comment]
Jack and I spoke today and have a proposed schedule ready to push tomorrow. We've adressed everything in this and #183 aside from this point:

_contact users for scheduling testing in advance_

We ought to look at React week/SPA week and ensure we give some time during the schedule for each team member to line up some users
