### ISSUE TITLE
Short and simple intro to time and space complexity 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#154]
Nothing scary or detailed, but it would be useful for people to have a passing understanding of the implications of using different approaches to solving problems in code. At the very least:
- why some sorting or search algorithms take longer than others
- time vs space complexity and where they might actually matter
- how to recognise when these might be an issue in your own code
- approaches to addressing the issues, e.g. creating lookup tables 
- Depth-first search with tree/graph structures 
- what the hell is Big O notation

This is almost certainly belongs in the second half of the course--quite possibly as one of our Wednesday talks.

**Comment by oliverjam** [comment]
https://medium.com/basecs might be useful here. Not sure if she has anything on Big O though

**Comment by sofer** [comment]
Keep this open until we find a speaker and slot to deliver this for FAC19.

**Comment by Albadylic** [comment]
Will be delivered by Reuben and I on Monday 2-4pm

**Comment by sofer** [comment]
This is now planned to be a one-day project with an intro at start and presentations at end of day and to be put into a form that will allow it to be delivered by anyone for FAC20.

**Comment by reubengt** [comment]
Excited to see how this pans out. 

At its current state the workshop goes over big O notation and two search algorithms(linear and binary) to show why one is faster than the other.

Will be posing the following as prompts for the students to do their own research.

- how to recognise when time/space complexity might be an issue in your own code 
- approaches to addressing the issues.

very keen to see how this would evolve over time, the majority of instructional material online teaches this with the objective of clearing programming interviews, but I'd rather see this workshop help students gain an understanding of where this information is useful in day to day programming.

**Comment by oliverjam** [comment]
@reubengt how’d it go?

**Comment by reubengt** [comment]
@oliverjam they did some great research! The presentations covered different things and they found/created examples in javascript for reducing time complexity.

I think the format worked well, a quick introduction with a few prompts for a day of research done in teams.

They also kept a good balance between practical code examples vs theoretical discussion, and learned things they can start  applying immediately in practice interviews(eg: using a hash table/object to avoid nested for loops when working with arrays)
