### ISSUE TITLE
Standardising our Tuesday talks

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#155]
Although having improvised talks on any subject that a speaker wants to talk about is great and should be retained, the speaker slots may be too important to be left entirely to chance. It might make sense to standardise the Wednesday talk topics (and possibly eventually the slides) and treat them as an opportunity for more experienced alumni to give talks on important material that we might not otherwise have time to cover. A possible example of this is #154, but there are many others.

**Comment by sofer** [comment]
To do: decide on the 10 topics for the first 10 weeks of the programme.

**Comment by jackherizsmith** [comment]
Jack and Gregor to meet and discuss speaker strategy as part of the handover of organising these, and Fridays', talks.

**Comment by sofer** [comment]
@jackherizsmith to lead on this.

**Comment by sofer** [comment]
Action: @Albadylic and @jackherizsmith to catch up weekly for 15 mins on Monday

**Comment by jackherizsmith** [comment]
Action: Jack and Gregor to add potential speaker topics to CF handbook
