### ISSUE TITLE
SUMMARY.md

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#158]
Raising this issue to clarify the structure for our GitBook. I've noticed as we're adding the second half of the course that the sidebar is growing quite long. We may also want to split up the documents folder into sections (e.g. before the course, etiquette, Friday...) & we could have sections for "First Half" & "Second Half". See [this one](https://founders-and-coders.gitbook.io/tech-vs-abuse/-M-Ativ3E6qRasTFMIXV/) for comparison. 

Risks:
Breaking it down into sections and nesting more things dilutes the salience of having one central place for information.

**Comment by oliverjam** [comment]
I'm happy to divide it up similarly to the TvA one. Especially if we're going to have more "top-level" sections like "Student Handbook", "Precourse", "Coursebook" etc

**Comment by sofer** [comment]
@Albadylic to come up with a suggested new structure.
