### ISSUE TITLE
Week 17

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#162]
It might be time to start thinking about what we'd like to include in Week 17. In particular: 
- [ ] workshops to further learning
- [ ] presentations of TFB projects - to funders? to PO's?

**Comment by sofer** [comment]
@Albadylic to schedule a time to discuss with @sofer

**Comment by sofer** [comment]
Requests:
- more structured interview/employment prep
- "It would be cool to have some time to go over the design of our projects. I found bobby's design workshops we had on tuesday morning when we were in space 4 to be really insightful! It would be cool to do something similar to that"

**Comment by sofer** [comment]
- Mon/Tues/Wed - 3 day-long project days.
- Thurs/Fri - Employment prep + Talks at 2.

**Comment by Albadylic** [comment]
Closing since week is now complete
