### ISSUE TITLE
Make a 90-min space in the schedule for community engagement

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#164]
We need 90 minutes as a placeholder for community engagement. We could perhaps shift the Wednesday speaker slot to a Tuesday and make the community engagement at 4:30 on Wednesday. Tech for Better on Tuesday could also be shortened by making it a conversation (as for FAC19), not a discovery workshop. Employment prep could also be shortened in Weeks 1-8, shifted to a Wednesday straight after lunch and doesn't have to start from Week 1. If we end up not using the community engagement time (for whatever reason), students can continue to work on their projects at the allotted time.

**Comment by sofer** [comment]
Discussed and agreed. I'll make a pr.

**Comment by jackherizsmith** [comment]
This has been successfully implemented
