### ISSUE TITLE
Recommend Postwoman

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#165]
We've always recommended Postman as an API explorer tool, but https://postwoman.io/ is a really cool alternative.

It's open source (Postman took ~$50m in Series B~ [$150m Series C](https://blog.postman.com/postmans-series-c-funding-and-the-future-of-apis/) 😆  funding), a web app (better for Chromebooks) and started by a Black woman. I honestly think the UI is simpler/clearer for what our students would use it for too.

Thanks to @yvonne-liu for the suggestion

**Comment by sbinlondon** [comment]
I would also recommend [Insomnia](https://insomnia.rest/). I remember being incredibly confused by Postman when we used it in FAC14 and then in my first week on the job my tech lead introduced me to Insomnia and it felt so much more intuitive and clean and I was actually able to use to to explore our API 😅

**Comment by oliverjam** [comment]
Wow how have I never seen Insomnia before. It's so simple! Maybe we need small introductions to browsing an API/building your own API using tools like these

**Comment by sbinlondon** [comment]
Yes!! That would be super cool. API design is really fun and I think a good concept to introduce at some point, even as just a 'this is something you could explore further'. I'd love to help out with writing about/presenting this topic, if you still have guest talks/workshops/etc? Or maybe just collabing on here.

**Comment by oliverjam** [comment]
That would be great, thanks for offering. I'm not sure if it would be best structured as a talk or a workshop within the curriculum. Currently Postman is just touched on in this (slightly long) [REST API workshop](https://github.com/oliverjam/learn-rest-apis#postman). I know quite a few of FAC19 came out of that still quite confused about how to use Postman 😅

I also wonder if there should be an intro in Week 2 when they start using 3rd party APIs, then another in Week 7 when they are building their own.

**Comment by jackherizsmith** [comment]
I have heard great things about Insomnia, and Postwoman also looks awesome. We (#19) were using Postman by default, having not explored alternatives (unlike other tools: HackMD -> Notion, Zoom -> Jitsi, Github -> Jira, etc). So it would be cool to offer these too or instead.

**Comment by sbinlondon** [comment]
> I also wonder if there should be an intro in Week 2 when they start using 3rd party APIs, then another in Week 7 when they are building their own.

This sounds like a great idea. Intro in week 2 with a super well-documented API so they can get used to exploring one that exists using Postwoman/Insomnia and hopefully feeling very comfortable with that. And then have that solid foundation to build their own on top of. Maybe even if there's time get them to do some API documentation and have the groups explore each other's APIs, to get them in good docs habits 😉 (Sorry if any of this _is_ already covered btw, it's been so long!)

But yeah let me know when you start working on this stuff how I can help, or if you want to do a workshop together or something.

**Comment by sofer** [comment]
Ready to close.
