### ISSUE TITLE
Week 2 recommended api addition (Novara Media)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/coursebook#179]
I just saw that Novara Media has an public api (https://novaramedia.com/api/)
Thought it could be added to the [list recommended apis](https://github.com/foundersandcoders/coursebook/blob/master/week-2/project.md#recommended-apis)?

**Comment by sofer** [comment]
Moved link: https://github.com/foundersandcoders/coursebook/blob/master/curriculum/http/project.md#recommended-apis

**Comment by oliverjam** [comment]
Thanks for the suggestion! I think we want to keep the list pretty short though, and focus on APIs that are really well-documented so teams don't go down rabbit holes trying to figure stuff out.
