### ISSUE TITLE
"How to be a good mentor" guidance

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#182]
Review current documentation and edit it to be suitable for complete beginners, too (i.e. how to help people how to learn).

**Comment by sofer** [comment]
https://github.com/foundersandcoders/master-reference/tree/master/coursebook/mentorship

**Comment by Albadylic** [comment]
May be related:

https://github.com/foundersandcoders/london-programme/blob/master/cf/docs/mentor-prep.md

**Comment by sofer** [comment]
Still assigned to @oliverjam  :-)

**Comment by oliverjam** [comment]
@jackherizsmith has written something, will put a PR up

**Comment by sofer** [comment]
@jackherizsmith now in charge of this one and to make a wip pr of a new document.
