### ISSUE TITLE
Possible changes to Design sprints and Weeks 11-16 schedule

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#183]
It feels like a significant tactical error to be running design and build sprints back-to-back. I mean, what happens if the user feedback comes back negative? The PO and the team need an opportunity to sit with the prototype for a week or two before committing to the build. How would we feel about the following schedule?
- Week 11: User-centred design
- Week 12: TfB Design sprint
- Weeks 13-14: Student project build
- Weeks 15-16: Tech for Better build

**Comment by sofer** [comment]
Having talked to some of FAC19, let me adjust this suggestion:
- Having a full week for design is too much
- Having so much time is unhelpful because it encourages over-ambitious product prototypes

Updated student project schedule:
- Ensure that students have each decided on a problem statement + formed into teams + conducted initial user research before Week 11 (we can use the Tech for Better or Community time in Weeks 1-8)  
- Run a compressed version of @bethanyios and @jc2820's discovery and definition sprints back-to-back
   - Day 1: AM - Workshop 1: Discovery; PM - Workshop 2: Definition
   - Day 2: AM - Figma workshop + prototyping; PM - finish prototyping and do user testing.
- Day 3: AM - presentations and product planning; PM - start the build 

Tech for Better
- Week 11: Initial workshop with client to create problem statement and prepare for user research
- Week 12: Half-day Discovery workshop with PO
- Week 13: Half-day Definition workshop with PO + half-day prototyping and handover to PO for user testing; feedback from PO
- Week 14: Day 1: Product planning and prototyping; Day 2: start build

**Comment by sofer** [comment]
@Albadylic to review and respond by July 15.

**Comment by sofer** [comment]
FAC19 feedback: we may want to think about introducing more time to reflect on product features and architecture between Crazy 8s and prototyping. The jump from definition to prototype didn't leave a lot of space for thinking about what it is realistic to build in 2 weeks and also how to do it.

**Comment by Albadylic** [comment]
FAC20 Timeline for TFB:

Week 2: Gregor gives introductory talk to cohort
Week 3 - 9: Product Owner conversations (2 PO's, cohort in two groups)
Week 10: Cohort choose teams & teams choose projects & Gregor gets in touch with PO's
Week 11 Day One: SP Discovery from 10-16. 16-18 is TFB Discovery Workshop
Week 12 & 13: PO's conduct User Research
Week 14 Day One: Definition Workshop
Week 14 Day Two: Product Ownership workshop
Week 15 & 16: Product Build & User Testing - PO's attend reviews/planning
Week 17 Day Three: Tech for Better Showcase
