### ISSUE TITLE
Update schedules for Weeks 1-9 to fit in with the new default schedule

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#186]
See #177

**Comment by Albadylic** [comment]
Jack and Gregor to discuss on Wednesday morning

**Comment by jackherizsmith** [comment]
- [ ] Fix broken links
- [ ] Move spikes back to replace Tech for Better on Monday pm
- [ ] Move Tech for Better to Tuesday pm
- [ ] Update links with timing, as per week 1
- [ ] Add learning outcomes where possible, as per week 1

**Comment by jackherizsmith** [comment]
Jack to add SP idea selection to Wednesday week 9

**Comment by jackherizsmith** [comment]
Need to ensure good timings for FAC21
