### ISSUE TITLE
HTTP game remote

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#189]
@sofer we should find a way to do the HTTP request intro remotely. Might be tough since they can't mill around the room and talk to each other.

**Comment by sofer** [comment]
I agree. It would be tough.

**Comment by oliverjam** [comment]
Okay I'll remove from next week's schedule and just extend the first-class functions workshop

**Comment by jackherizsmith** [comment]
This is now going ahead, altered for zoom with people renaming themselves and reading out their description when someone else mentions them.
