### ISSUE TITLE
Design bursts

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#191]
- [ ] positive feedback from fac19, would like to extend this further (animations, SVG, data vis?)
- [ ] CF handover suggests run by alumni, but would be better for curriculum mentors to lead
- [ ] make plan for what exists, the sequence, what are the gaps, and prep mentors for delivering them

**Comment by oliverjam** [comment]
They used to be run by alumni but that's changed.

We always planned for there to be one a week, but ended up transitioning them into the employment sessions in the second half of the talk.

**Comment by sofer** [comment]
We have time carved out on Wed pm as well for this. One line of thought was that we start the employment prep by focusing on a portfolio page and the design bursts could support that.

**Comment by sofer** [comment]
@jackherizsmith is going to look at the existing material we have, decide on the sequence and identify any topics that need re-writing.

**Comment by oliverjam** [comment]
Looks like we're going to keep the first 4 weeks of design bursts as they are, then transition into using that time for employment prep. @sofer and @jackherizsmith will take a look at how to frame that
