### ISSUE TITLE
Add student agreement

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#193]

**Comment by jackherizsmith** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSf94xwjoaV2XRAxLBh84FmW8JpLe2MJa058LlLNoP0il0mM-A/viewform

**Comment by oliverjam** [comment]
Should this be in the handbook (bearing in mind it's public)? Feels like something that should only be emailed to confirmed course participants, rather than anyone who happens to be working through the curriculum

**Comment by jackherizsmith** [comment]
Yeah I see what you mean. I was adding it here in case it helped with the issue. What is the student agreement you were looking to add?

**Comment by oliverjam** [comment]
I don't know, I didn't realise this was my issue 😆. No memory of opening it, but looking at it now I can't see much point to this. I think I assumed the student agreement was some kind of document they had to read, rather than an interactive form.
