### ISSUE TITLE
Facilitate learning circles

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#194]
Create a space for students to work together on a given week's focus with alumni volunteer

**Comment by jackherizsmith** [comment]
Came up at SGC, to create Slack channel and complement this with coming to me directly to be linked up confidentially

**Comment by jackherizsmith** [comment]
Have created a channel #fac20-revision-circles with accompanying message integrating thoughts on #117

**Comment by sofer** [comment]
Will review this again towards the end of FAC20.

**Comment by jackherizsmith** [comment]
It was good to trial it - people ended up not using this, or the even more supportive office hours.

This can all be replaced by #254, and potentially replace employment mentors also
