### ISSUE TITLE
Readme links are broken

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/coursebook#195]
Hi!

Cool knew coursebook! 👀 

Great job everyone involved

Tiny thing I thought you should know that at the topics section the week links appear broken:

https://github.com/foundersandcoders/coursebook#topics

I guess due to #188 

If I get a chance I'll make a PR but thought I'd flag in case someone else gets a chance before me (also not sure of the correct process) :D

**Comment by oliverjam** [comment]
Good catch thanks. Not sure we have a process yet, should probs at a CONTRIBUTING.md
