### ISSUE TITLE
Feedback survey // user manual updates

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#197]
Both scheduled for Friday 4.45. Feedback would make more sense at the start of the week, perhaps 10 mins before lunch Monday or Tuesday?

**Comment by jackherizsmith** [comment]
Move feedback to mentor intro slot
presentations shorter and sgcs earlier and 45 mins

**Comment by sofer** [comment]
Surveys on Mondays at 10:05-10:10. Ready to close.
