### ISSUE TITLE
Weekly themes

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#2]
1. Inclusivity/Teamwork/Web dev basics
    Slightly tough one because the LOs are all over the place. This week includes git, a11y, DOM manip, mobile-first CSS etc
1. HTTP
1. Testing
1. Node/server-side
1. Databases
1. Authentication
1. Express?
    Not convinced that a specific server library is really the most important takeaway here. We're going to cover templating in vanilla JS, making a REST API and good server design.
1. Fullstack app

**Comment by arrested-developer** [comment]
>Slightly tough one because the LOs are all over the place. This week includes git, a11y, DOM manip, mobile-first CSS etc

I think Git might be the most universal one across the whole week?

>Not convinced that a specific server library is really the most important takeaway here. We're going to cover templating in vanilla JS, making a REST API and good server design.

Strongly agree on bringing in REST API best practices.

**Comment by oliverjam** [comment]
Git is definitely the thing you'll use most, but that's true of every week going forward :/

**Comment by bobbysebolao** [comment]
Looks good! Maybe 'Teamwork & Toolkit' is a short way to sum up the first week?
