### ISSUE TITLE
When to intro the scrum master role?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#204]
It (unexpectedly) got intro'd in Week 1. Do we want to continue with this or roll it back.

Either way, having intro'd it, we might want to provide some more info in Weeks 2 or 3 for FAC20 and then decide whether we want to intro scrum master early in FAC21.

**Comment by sofer** [comment]
This is where the concept formally gets intro'd now: https://hackmd.io/@fac/S1ZTP6UcI#/2/14 (in Design Week!)

**Comment by oliverjam** [comment]
I think probably Week 2 makes sense. That way everyone at least gets a change to try out writing issues etc in Week 1.

**Comment by jackherizsmith** [comment]
I agree. Spend a week perhaps struggling to organise effectively then introduce a role where their responsibility is to support the team to code more effectively. Do we need to introduce stand ups, blockers etc? Or enough just to say this is why a scrum master exists and see where they take it?

**Comment by oliverjam** [comment]
I think on a ~2 day project trying to enforce a normal sprint structure would be counter-productive. The two pairs should be communicating/swapping far more frequently than once or twice a day.

I guess we could condense it all down and have them to do a morning and afternoon standup, on top of normal pair-swapping etc

**Comment by sofer** [comment]
Closing in favour of #205
