### ISSUE TITLE
Roles in projects from Week 1

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#205]
FAC19 were given roles for spikes, but I believe we removed them from the coursebook, because there was a feeling that they were confusing.

Do we want to maintain the roles in spikes or not?

**Comment by oliverjam** [comment]
I think we introduced them way back in Week 1 in-person but then never really used them after that. I am fully in favour of dropping them

**Comment by sofer** [comment]
It also sounds like there has been a but of role-playing in projects, too. 

For context, I started experimenting with roles from Week 1 very early (FAC2, perhaps?) in our history, but dropped in sometime around FAC6 (?), because it was causing a lot of confusion.

On the other hand, lightweight roles from Week 1 could possibly work. I am happy to revisit--but with caution.

**Comment by jackherizsmith** [comment]
Spike roles didn't work remotely at all for 19. It requires constant and irregular communication between four people, so doesn't work on video calls. Interesting idea that an author of a part of a presentation didn't do the research themselves, so the presentation as a whole is written and delivered by people who had to learn it from each other.

**Comment by jackherizsmith** [comment]
Regarding project roles, I think we could introduce themes as early as this week. Rather than explicitly having a UX lead, Dev ops etc, we could suggest that for if/when there is indecision, a team decides in advance who will be responsible for

- design considerations, championing user stories
- project set up, architecture and third party tools
- making sure code is readable and concise
- removing barriers, managing issues, assessment criteria

Everyone is involved in every part, but one person has a final say on their area if there's indecision.

**Comment by oliverjam** [comment]
Another thing that came up in my team SGC was focusing on the role/jobs you're least comfortable with. We should encourage people who struggle with design/CSS to take on responsibility for the look and feel etc.

**Comment by jackherizsmith** [comment]
>a team decides in advance who will be responsible for
> - design considerations, championing user stories
> - project set up, architecture and third party tools
> - making sure code is readable and concise, works as expected
> - removing barriers, managing issues, assessment criteria

When would be best to suggest this? Wednesday morning as teams are being put together, or tomorrow with the issue estimation slides?

**Comment by oliverjam** [comment]
Probably fits best as part of the slides on project management

**Comment by jackherizsmith** [comment]
Are there other things we can be introducing for people with other responsibilities, as I'm conscious scrum and design tend to get more direction & resources than deployment and code quality? #215

**Comment by jackherizsmith** [comment]
#212 - employability also relevant for this discussion.

**Comment by sofer** [comment]
Intro the 4 "aspects" of project management in Week 1 and then intro them as roles in Week 2. Add to existing slidedecks.

**Comment by jackherizsmith** [comment]
https://hackmd.io/94kUUyofSJOKWrLQ4VMJlg
