### ISSUE TITLE
Team SGC guidance

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#207]
- We might want to strongly encourage people to use the large-group SGC method, i.e. silent adding to SGC board before discussing.
- It may be worth suggesting discussing each point in rounds as a means for ensuring that one or two people do not dominate the discussion and everyone has a say (although we may also not want to mandate this too strongly as it can interrupt the flow of conversation and we don't have a lot of time in Team SGC)
- Make sure that the facilitator does not feel they need to respond to every issue and, except for reading out each point, doesn't talk more than the others
- We may want to assign somebody as facilitator, timekeeper, and note taker and perhaps have the 4th person play a "reflective" role at the end of the session to provide a closing response to the SGC
- and don't forget to make time to update user manuals

**Comment by oliverjam** [comment]
I asked my group if they'd rather I facilitate or observe, and they went for facilitate. I ran it exactly like the main SGC—gave them 7 mins to silently add to the HackMD, then went through point by point. Seemed to work pretty well

**Comment by Albadylic** [comment]
I suggested they follow the same structure of open a HackMD, reflect individually for 5-10 minutes and add points there, appoint a facilitator and spend 20 minutes discussing. I said I'd be quiet unless they asked me to speak. They took notes without my suggestion and went through point by point making sure everyone got a chance to speak. It went well but there was a bit of a rush to finish up in time. I wasn't asked to speak but couldn't help doing a couple of agreement waves 👐

**Comment by jackherizsmith** [comment]
I started by saying I was present and if they would like any input to let me know, then left them to discuss the week. I did some waving, and clarification on project teams in future weeks

**Comment by sofer** [comment]
- First 2 weeks to be facilitated.
- 2 roles: facilitator and time-keeper
- Guidance in course book needs to be changed.
