### ISSUE TITLE
Database setup script

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#209]
One thing that might ease the pain in DB week is if we had a small intro to writing your own custom setup scripts to set env vars, run shell commands etc to make sure the DB is initialised properly. This could come after they've felt the pain of configuring it over and over and messing stuff up.

A script like this would usually be Bash, but that's probably a little much at this stage. Better to get them practicing more JS, but in a different context than usual (using `fs` and `exec` to do stuff on their local machine rather than standard HTTP servers).

**Comment by jackherizsmith** [comment]
Could be unnecessary for two lines of SQL.

Could introduce a scripting workshop
