### ISSUE TITLE
Data structures

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#210]
Is there any space in the early weeks of the curriculum to cover the basics, a bit like we do with "design bursts".

I am thinking:
- Arrays
- Linked lists
- Stacks
- Queues
- Hash tables
- Trees
- Heaps
- Graphs

See e.g.
- https://github.com/trekhleb/javascript-algorithms
- https://www.educative.io/blog/javascript-data-structures
- https://medium.com/siliconwat/data-structures-in-javascript-1b9aed0ea17c

**Comment by oliverjam** [comment]
It's pretty much packed to bursting 😆

Maybe this should be weighted towards the second half, with a focus on interview prep? Everyone has gotten by fine building basic web apps without any of this stuff until now—I find they're more useful for getting a job than anything else

**Comment by Albadylic** [comment]
I agree with @oliverjam that this ought to sit in the second half and framed in regards to interview prep.

**Comment by sofer** [comment]
I am not sure just treating these topics as interview prep is doing them justice, but I do take the point about us already being packed to bursting. I guess as long as Wednesday pm is available, we could introduce a "Data structures and algorithms" hour and then move onto interview prep at 3 (or later). 

Perhaps there is something we could do around introducing two new data structures together, then introducing a problem that could potentially be solved with them, then asking people to have a go at solving the problem and comparing the different approaches. It might be a challenge to do all of that in an hour, but I am open to other suggestions.
