### ISSUE TITLE
The new/old software developer apprenticeship standard

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#213]
https://www.instituteforapprenticeships.org/media/4392/software-developer-st0116-standard.pdf

Published today.

Planned for first delivery from January 2021. 

It looks pretty sensible and there are some gaps e.g. #210 that it will be an interesting and worthwhile task for us to fill before then.

**Comment by jackherizsmith** [comment]
Dan and Oli to meet to discuss for FAC21

**Comment by jackherizsmith** [comment]
All to check which knowledge skills and behaviours are covered in the current curriculum. When we reconvene we will be able to say what percentage of each duty is currently being covered.

**Comment by oliverjam** [comment]
Here is the spreadsheet mapping our current curriculum to the standard
https://docs.google.com/spreadsheets/d/11oG_3cYs6fxsRZhEVc2fJMdsP8lgfTbUPAy5ttQfx48/edit#gid=0

**Comment by sofer** [comment]
@oliverjam to lead. @sofer to be available to support, if needed. Reporting back net week.

**Comment by oliverjam** [comment]
I appear to have no memory of what specifically I agreed to lead on here 😅. @sofer what exactly am I reporting back on?

**Comment by sofer** [comment]
### Outline timetable
- Nov 2020: mapping standard to our existing learning outcomes and coming up with a new set of outcomes that leaves no gaps
- Dec 2020: identifying new material required to meet the new outcomes and creating a new 12-week timetable
- Jan 2021: writing that new material
- Feb 2021: writing a new student handbook that outlines all the criteria for the apprenticeship standard in more detail than the learning outcomes and organised by knowledge, skills and behaviours.
