### ISSUE TITLE
Allyship reminders every couple of weeks

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#216]
Just something quite short about different kinds of interactions. Grad feedback.

**Comment by sofer** [comment]
Invite @yvonne-liu to the circle at which this gets discussed.

**Comment by sofer** [comment]
Change of tactic. @Albadylic to take lead with @jackherizsmith to adding list to CF documentation of issues to bring up regularly at SGC and consult with @yvonne-liu.

**Comment by Albadylic** [comment]
Moved to [CF docs](https://github.com/foundersandcoders/course-facilitator-handbook) repo
