### ISSUE TITLE
New Slack channel: "office-hours" 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#218]
To encourage students to ask questions of alumni and to encourage alumni to respond to them.

@yvonne-liu 

(from fac19 exit feedback)

**Comment by jackherizsmith** [comment]
I think this could do with more definition, to understand what this means in practice - how is it different from #facoverflow and the new #fac20-revision-circles channels? Is it related to employment? Which might overlap with plans to connect more senior alumni with students whose professional interests overlap (as employment mentors).

**Comment by oliverjam** [comment]
Yeah not sure this makes sense as yet another Slack channel. Would rather this be scheduled times for alumni/team members to answer questions (and hopefully save them being shoehorned in after workshops/talks when everyone else has to sit and listen)

**Comment by oliverjam** [comment]
Action: set up a Slack channel to be used by students to ask for mentors to meet with them and answer question, and also for alumni to post with times they are available for students to ask them questions

**Comment by jackherizsmith** [comment]
Action: encourage alumni to introduce themselves and highlight availability for students to reach out either in the channel or directly.

What other opportunities can we provide people who are struggling most to make sure they take this opportunity vs people who are more driven to take advantage of this?

Perhaps restructuring the course in the future to build in office hours.

**Comment by oliverjam** [comment]
I'll put in an hour or two slot on Thursday and encourage people to either publicly respond or DM me

**Comment by jackherizsmith** [comment]
Action: Gregor to write notes for mentors

**Comment by Albadylic** [comment]
Have posted guidance and mentors have been volunteering. Ready to close?
