### ISSUE TITLE
Disclaimer for independent learners

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#219]
We encourage people to use our curriculum to learn web dev even if they don't participate in our course. However we should highlight in the readme that using the curriculum to self-learn does not mean you can say you attended/graduated Founders and Coders

**Comment by jackherizsmith** [comment]
I wonder if we can offer something like a certificate, or advise on how people can refer to having completed our curriculum on LinkedIn for example. E.g. people who do the programme tend to add it as a full time position, whereas we could advise that people can add Founders and Coders to their "Courses" section?

**Comment by oliverjam** [comment]
I wouldn't be comfortable even with that, since we have literally no way to enforce it or verify that people really went through the curriculum.

We'd at least need something like the FreeCodeCamp model, where you have to submit projects that get verified before they give you a certificate.

**Comment by oliverjam** [comment]
@oliverjam to add a disclaimer to the readme

**Comment by jackherizsmith** [comment]
We need to add to the disclaimer ( [what you _cannot_ do](https://founders-and-coders.gitbook.io/coursebook/#license) ) that people cannot call themselves FAC grads

We might need accreditation for apprentices anyway so we should consider this for graduates
