### ISSUE TITLE
Number the tasks/challenges in workshops

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#226]
For reference (sgc wk2 feedback) @jackherizsmith has offered to address this.

**Comment by sofer** [comment]
@jackherizsmith to check with @oliverjam to check what's easiest for him.

**Comment by oliverjam** [comment]
Sorry just saw this after discussing on Slack. The main difficulty with this is maintaining the markdown files. Once you start hard-coding numbers into headings it becomes really hard to keep them in order as people edit the workshop in future. We could try and rely on HTML's automatic numbering of `<ol>`s, but that has it's own awkward markdown-formatting issues.

```md
1. ## A heading inside an `<ol><li>`
   The rest of the content beneath the heading must be indented to be part of the same `<li>`
1. ## Another heading inside a new `<li>`
   More content
```

**Comment by jackherizsmith** [comment]
I think your solution is much better and could just be a part of updating workshops, but I think it's your call on if this is worth it vs leaving it and people get used to referring to challenges by name.

**Comment by oliverjam** [comment]
I'm not sure the small convenience gain for students occasionally referencing sections by number instead of by title is worth the maintenance burden tbh.
