### ISSUE TITLE
More support before workshops

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#228]
People have mentioned a few things on this so combinng it into one issue (and creating an SGC label for things we add related to cohort feedback).

I've added checkboxes to capture which things we want to / can address or not.

- [x] Sometimes the solutions require information not provided in the workshop
- [x] People need time to read through workshop before starting to code
- [x] A 'walkthrough' in advance of starting was suggested, where a mentor writes a solution out for everyone to see how to do it (... like a classroom...?)

**Comment by sofer** [comment]
Closing.

**Comment by oliverjam** [comment]
How was this resolved?

1. I tried to write most workshops to be self-contained and not require additional googling, so if they could open issues on any they feel need additional clarification that would be helpful
1. Have mentors been telling them to jump straight into coding? Do we need to make it clear that they are absolutely supposed to spend time reading the workshop before they start?
1. I'm not sure we want to become even more reliant on mentor work
