### ISSUE TITLE
Add cross-browser testing to project acceptance criteria

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#238]
How possible would it be to have a site that starts a bit broken across different browsers for people to debug and fix?

@oliverjam and I briefly once discussed debugging / testing across browsers, and Johanna mentioned it in her week 3 Friday talk so there would probably be interest and value.

**Comment by oliverjam** [comment]
We should start introducing additional browsers as acceptance criteria in later projects so they get some experience checking everything works and fixing small inconsistencies.
