### ISSUE TITLE
Rename cleaner? 

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#241]
It is becoming de facto for more than just cleaning, including:
- social sec
- SGC faciliator
- etc (I think FAC19 made up jobs for cleaner to that got forgotten about)

Essentially sums up to cohort scrum master for that week. That's not my suggestion, just seeing it as becoming a servant-leader role.

**Comment by oliverjam** [comment]
Did pre-remote cohorts overload the cleaner role in a similar way? My only concern is that once we're back in the space cleaning up is already quite a lot of work. Maybe we should have a separate other role for these things?

**Comment by jackherizsmith** [comment]
Agreed, maybe just worth it for FAC20 then? Could be more of an SGC thing in that case. I'll close this.
