### ISSUE TITLE
Navigating conflicts workshop?

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#247]
Probably too far in for FAC20, but this has been suggested. There will be tensions during the course and it would be helpful for everyone to be given the tools to communicate effectively (e.g. [NVC](https://www.nonviolentcommunication.com/learn-nonviolent-communication/4-part-nvc/)?)

**Comment by oliverjam** [comment]
This is definitely something we need, possibly in Week 1. I think team SGCs were _supposed_ to facilitate this, so maybe we use the slot in Week one to do very tightly managed SGCs with staff, maybe with a presentation at the beginning or something.

@yvonne-liu I'm sure you have useful thoughts so would be good if you came to the next circle to discuss 🙏

**Comment by jackherizsmith** [comment]
I have also reached out to Lucy at InFact, on Yvonne's recommendation, to see if she would come and give a talk about NVC.

**Comment by jackherizsmith** [comment]
Action: reflect on Lucy & Max's talk, thinking about training for future cohorts

**Comment by oliverjam** [comment]
@jackherizsmith how did this go yesterday?

**Comment by jackherizsmith** [comment]
I think it went well, it was their first time delivering it so good practice for them, and they're keen to deliver it earlier in the course next time which is great news. We'll see what the FAC20 feedback is but overall I'm pleased that they're keen to do it for future cohorts

**Comment by oliverjam** [comment]
Cool. Do you want to keep this issue open?

**Comment by jackherizsmith** [comment]
No I think this is resolved :)
