### ISSUE TITLE
The role of morning challenges

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#251]
As @yvonne-liu has pointed out the new curriculum sometimes means students miss out on practicing problem-solving skills. 

Morning challenges are supposed to provide a safe, time-boxed space for students to struggle and stretch themselves and practice googling stuff they don't understand. For example if they've already learned basic SQL syntax on Mon/Tue they can spend Wed morning practicing much harder advanced queries (that may be useful to them during the project).

Morning challenges should _not_ be a place where we introduce totally new topics, expect students to teach themselves or make them struggle with impossible riddles. For example the old waterfall challenge to "learn" callbacks 🙃

**Comment by jackherizsmith** [comment]
@Albadylic and @jackherizsmith to include as reminder to mentors in CF docs

**Comment by Albadylic** [comment]
Moved to [CF docs](https://github.com/foundersandcoders/course-facilitator-handbook) repo
