### ISSUE TITLE
Self-cleansing tests?

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#255]
Not sure if this is already covered in testing week, but I've seen lots of tests that don't remove their impact once completed, if that makes sense.

**Comment by oliverjam** [comment]
Have you got an example?

It is briefly touched on in the integration testing workshop here: https://github.com/oliverjam/learn-integration-testing#testing-ui-logic

But it could definitely do with a little explanation of why it's a good idea 😅

**Comment by jackherizsmith** [comment]
Great question I'm afraid not. Just scanned last week's projects so could have been week before, basically a lot of posts rendered on the page that were from the tests not user input. I'll keep searching. 

There is [this arrange act assert thing](https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80) but that's separate.
