### ISSUE TITLE
One day project for beyond technical web development

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#258]
Wondering about other web development things not covered in this course. Is it worth spending any time on, for example, SEO? Even just basics about what improves rank and so on? More relevant for grads that join smaller (e.g. two people) companies, which some of FAC19 have done.

I guess this could work as a one day workshop after everything finishes, not sure how people would see progress / success.

**Comment by oliverjam** [comment]
I think we could do a one day project in the second half of the course where we introduce a static website tool (something like [Eleventy](11ty.io/), which the FAC site and my personal site use).

We could have them build out a marketing site/personal blog, including best practice SEO stuff, social preview images etc.

**Comment by jackherizsmith** [comment]
When would you suit you for this Oli? I think Thursday 12 November could be perfect in terms of the course timings.

**Comment by jackherizsmith** [comment]
Additional thoughts:
- Cookie pop ups
- Google analytics
- GDPR relating to these

**Comment by oliverjam** [comment]
That stuff is tough—I don't really know much about any of it so would struggle. I also have no idea what the threshold is for requiring cookie/GDPR notices.

A CMS tends to more than double the complexity of a static site project—we could do a basic git-based one like Netlify CMS but that doesn't tend to be a great solution for non-technical POs.

If this needs to fit into a single day we probably need all the time for the stuff I already have in mind:

1. Difference between server-side rendering (Express), client-side rendering (CRA) & static rendering (Eleventy)
1. How to use Eleventy to generate a website from data + templates
1. Important stuff websites need that they will have neglected for now
   - Meta tags for link previews
   - Page descriptions, keywords & site maps for SEO

**Comment by oliverjam** [comment]
Oh and I'm happy to do it any time, just need to spend a day writing it up at some point. This has been my bread and butter lately so shouldn't be too difficult.

**Comment by jackherizsmith** [comment]
Awesome in which case let's go with your existing plan. Thursday 12 would be cool.
