### ISSUE TITLE
Simple CSS tricks that will impress non-devs

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#259]
Similar to the SEO issue #258 I think it could be worth spending some time learning some easy CSS that makes websites look great. Basically gimmicks, like how to make elements fade in as you scroll down the page, etc.

**Comment by oliverjam** [comment]
I gave a whole talk to FAC12 on this subject 😆
https://utilitarian-ui.netlify.app

This was sort of what Design Bursts were supposed to be

**Comment by oliverjam** [comment]
Sounds like I'm giving a variant of this talk again on Sep 8th

**Comment by jackherizsmith** [comment]
Only if you're happy to! I think people will love it and it will be a super helpful talk I think
