### ISSUE TITLE
Reading week checklist

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#265]
It might be useful to have a list of things you should probably know after the first half of the course. We have previously given this to some cohorts, but maybe we want to consider whether it's contradicting the advice to relax 😅

https://hackmd.io/@3h2qEDKEQXSZK4l2wloSMg/SJrDiJyBB

**Comment by sofer** [comment]
My main question about the checklist is what the relationship is between that and the learning outcomes and whether we might want them to be one and the same list.

**Comment by jackherizsmith** [comment]
Could include bold LOs for each week as reference / recap. Or suggest people review LOs (without directly recalling them)

Could think about an additional survey to self-assess progress against weekly LOs
