### ISSUE TITLE
React router dom in React Week

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#270]
Is it possible to cover this in React week? Otherwise we could try and squeeze in design week, or the beginning of build week 1. I think it will really help.

**Comment by oliverjam** [comment]
There's just no way 😬 but I agree it's super important and a lot of people misunderstand it and end up struggling on their projects

**Comment by oliverjam** [comment]
Maybe another one-day workshop that can be slotted in somewhere

**Comment by jackherizsmith** [comment]
could be in one of the design week spikes @Albadylic 

QA - Cypress
UX - Storybook
Scrum - ???
Deployment - react-router-dom?

**Comment by Albadylic** [comment]
I think I'd rather we leave the Tech Spikes open for roles to decide what they might like to explore. In the past there's been mixed feelings about most technologies (e.g. on my cohort none of us used Cypress but a lot of us used Airtable).

On the flipside, a spike without direction may not be a good use of time.

**Comment by Albadylic** [comment]
Slightly off topic from the original point, however:

Spikes in Design Week should be around a topic from a shortlist provided or if they'd like to explore something else they've heard about then that's cool too.

Todo: write the shortlist based on Jack's suggestions above.

**Comment by jackherizsmith** [comment]
I'm wary that we spent time working with technologies that we somehow found and weren't great (e.g. no idea how so many people ended up using Material UI) whilst other technologies that people loved (Cypress, Storybook) were discovered quite late on. So it would be good to make sure during these spikes that people's time is spent focusing on things we know are good, esp from FAC19's experience.

**Comment by oliverjam** [comment]
Yeah I would really like to encourage the FAC19 mentors not to pass the Material UI suffering on 😅 no idea where that came from, but I noticed it too late to stop it

We should probs carry on the spikes convo in #273
