### ISSUE TITLE
"API docs in README" as acceptance criteria?

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#271]
People in the user role this week felt redundant as they didn't any graphical design to do, and hadn't considered what their _users_ need - e.g. documentation for using the API. Could we include this in the acceptance criteria, as it's equivalent to an accessible front end?

(It will also help them to think about what they actually need from their routes especially those that are returning information)

**Comment by oliverjam** [comment]
Yeah absolutely, was just thinking about that this morning. It's really hard to code review an API with no docs 😅

**Comment by sofer** [comment]
@oliverjam still looking at the structure of Week 7, but @Albadylic to add 1-liner now.
