### ISSUE TITLE
Design week spikes

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#273]
Jigsaw based on project roles. We'll provide a recommended list of topics that they can choose from based on their project needs.

## QA

1. Cypress
1. Travis as a CI (or alternatives)

## UX

1. Styling in React (CSS-in-JS, Styled Components etc)
1. Storybook for documenting/building components

## DevOps

1. Netlify Lambda (using serverless functions for the few bits of backend you might need)
1. Airtable as a database?

## PM

1. PERT?

**Comment by jackherizsmith** [comment]
PM - Jira?

**Comment by oliverjam** [comment]
@Albadylic what's a PERT? @jackherizsmith 😬

**Comment by Albadylic** [comment]
I believe it's a method of estimation. @teenie-quaggard presented on [this](https://foundersandcoders.slack.com/archives/CUA4KPW3B/p1589364755054500) to FAC19

**Comment by jackherizsmith** [comment]
@jackherizsmith to speak with project mentors ahead of spikes to bring their own topic ideas, and facilitate discussion if groups would rather learn and build something else
