### ISSUE TITLE
Replace SPA Week with React Week

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#280]
I've had a lot of trouble trying to figure out a workable "Single-Page App" week. It's quite difficult to build anything substantial in the browser without either ending up with a spaghetti mess of DOM manipulation (which isn't really that different to what they do in Weeks 2 & 3) or you end up creating your own pseudo-framework.

The main benefit of Week 8 right now is practicing JS (especially client-side JS) a lot more. But since React is almost entirely regular JS I don't see much of a downside in getting that JS practice _whilst_ learning React.

I think we're doing our grads a disservice by not giving them as much time as possible to practicing the kind of code they'll actually end up writing in the industry. It's really difficult to teach a huge swathe of "modern frontend/JS" stuff without a framework. It also makes a lot of the resources students will find on the web less useful since they're so framework focused.

We currently have massive time-constraints with trying to teach all of React in a week directly before they start projects. It would be better to have two weeks where we can introduce React plus modern frontend concepts and possibly more ecosystem-wide stuff (like client-side routers or other libraries).

**Comment by jackherizsmith** [comment]
Does not impact cohort team structuring, and adds room for content - styled components, Cypress, Storybook, react router dom

**Comment by oliverjam** [comment]
Following discussion from the circle:

1. This makes sense
1. Shift React Week forward to Week 8
   - Maybe drop testing in favour of something directly React-related, since we can cover testing the following week
1. Week 9 becomes a more general "Real world apps week"
   - Using React to make it easier to focus on UX patterns like fetching data/loading/error messages
   - Also cover ecosystem stuff like React Router and testing (styling?)
1. Maybe move client-side rendering workshop from current Week 8 forward to Week 3

**Comment by oliverjam** [comment]
Oh sorry @jackherizsmith, didn't see you added the same notes 😅

**Comment by jackherizsmith** [comment]
Your notes are better :)

**Comment by jackherizsmith** [comment]
Could we rename this issue week 9, and "Real world apps week" week 10? this helps keep things consistent with things like the course calendar, speaker timelines etc

**Comment by oliverjam** [comment]
Yeah I guess. I've never thought of Reading Week as a "week" in the sense that it should have a number, but maybe that's more confusing for everyone.

**Comment by jackherizsmith** [comment]
Yeah I've been trying to remove references to week numbers to be honest, because no one thinks in numbers anyway and it makes the other scheduling confusing if things are counted differently. Thanks

**Comment by sofer** [comment]
@oliverjam to close when done.
