### ISSUE TITLE
The shape of a 12-week programme

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#288]
Assuming that we are dropping SPA week and bringing React week forward, then that is the first 8 weeks covered. There are then two obvious approaches to a shorter programme:
1. Introduce a new week of React and other topics; complete the student project in 3 weeks and drop the Tech for Better project;
2. Go straight into the student project and compress it to two weeks (or less); complete the Tech for Better project in two weeks.

If we went for the second option, there are a few things we could do to make it feasible:
- Insert some discovery and user research into earlier weeks, so that a bit of groundwork will have been done before the first project week;
- compress the design sprint to a couple of days;
- liberate the employment prep time on Wednesdays (and push it to the end of the course for those that need it);
- switch the emphasis of the first project from doing something new to cloning something that already exists;
- shorten the student project (to ~8 days) and expand the TfB project (to ~12 days).

**Comment by sofer** [comment]
Watching this week's Design Week presentations, I am impressed with how good they are how much thought and work has gone into the week. I am less sure that "cloning something that already exists" would be an improvement upon what we already do. I am also reminded of how challenging it would be to compress the time available.

**Comment by sofer** [comment]
General consensus: We drop Tech for Better from the programme and, subject to discussion at General Circle, we transition Tech for Better to a graduate programme.

**Comment by oliverjam** [comment]
Dependent on my work mapping the Standard to learning outcomes. We can't map out a 12 week programme until we know what we're missing/need to add. This can probably wait a few weeks.

**Comment by oliverjam** [comment]
One potential solution we've discussed: combine Student Project with TFB Project. This would still have a Product Owner from outside the cohort, but not a complete stranger who has applied for TFB and really wants to get a legit product at the end. We could either have graduate mentors from the community act as POs, or reach out to local university entrepreneurship programmes (or Year Here).

This would allow the cohort to get experience communicating with non-technical POs, working on someone else's idea, translating specs/stories to code etc (all Duties in the Standard) whilst allowing us to save the TFB time.

**Comment by oliverjam** [comment]
[from my and Dan's discussion today]

Do we want a single Final Project or two? We potentially have 4 weeks left at the end of the course (since React Week is moving to Week 8). It might be difficult for them to not have a "practice project"—there's a lot of pressure to get everything right when they only have one chance.

TFB projects have generally been vastly improved by all the mistakes made during Student Projects.

**Comment by oliverjam** [comment]
Suggested revised first 8 weeks:

1. Toolkit
2. HTTP
3. Testing
4. Server (with Express)
5. Database
6. Authentication (via 3rd party services)
7. API (with an extra DevOps focus)
8. App (React Week with some more introductory SPA stuff)

**Comment by sofer** [comment]
Closing, as this is covered in other issues.
