### ISSUE TITLE
Guidance on how to ask for help

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#290]
We should have a clear guide on how to get stuck and subsequently ask for help. It should cover how to read (and re-read) workshop instructions (e.g. sometimes reading on past the thing that confused you will help clarify). Also reading error messages (e.g. the important bit is right at the top above the big stack trace. There are line numbers for a reason).

> (No waiting between each step)
> 1. make sure you've understood the error / problem
> 1. google it
> 1. ask another team
> 1. ask a mentor

> Guidance for mentors not to help until you’ve shared what you Googled and tried
> Share your solutions with the group in case others are stuck

**Comment by Albadylic** [comment]
Include a step by step list for before you ask for help (based on steps outlined above).

How to realise when you're stuck and need to ask for help.

Cohorts should know how and when to ask for help.
