### ISSUE TITLE
Guidance on how to set up a project board?

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#292]
I don't know if this is by design, but teams in FAC19 and FAC20 were basically left to work out "what constitutes an issue" by themselves. Which I think is valuable and maybe we can close this straight away, or we could discuss the need for it.

**Comment by sofer** [comment]
We do briefly cover what constitutes an issue in the first weeks of the course in the [Issue management and estimation slides](https://hackmd.io/@fac/B1AL4V3ML#/). We may want to revisit the slides or provide more detail in Design Week.

**Comment by Albadylic** [comment]
We may like to outline what a project board should look like and more detail on what should be contained in an issue.

We might like to include a workshop in Design Week. 

Jack to review boards and take notes in presentations on improvements to process. 

The current cohort seem to be using Jira for project boards.
