### ISSUE TITLE
Clearer full stack build sequence

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#295]
i.e build the frontend first (and how to mimic the backend simply?)

**Comment by Albadylic** [comment]
FAC19 built the backend first then the frontend. FAC20 almost did but we caught it and advised against. Building decoupled frontend first is preferable. 

This may stem from SPA week coming after REST API week. 

We could address this in the new SPA/React week.

**Comment by oliverjam** [comment]
This will be covered in the new Week 9 (full-stack React etc). Possibly including Next (#342)
