### ISSUE TITLE
Command-line basics

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#296]
Lots of people still rely on using a GUI file browser to create/delete files in their projects. It would be good have a better intro to basic file system commands.

Maybe learn a new one each week on a Monday morning or something?

**Comment by sofer** [comment]
@oliverjam to research online dev environments, such as Codespaces, that we might be able to include in coaching resources, as a first step. Reporting back in a week or two.

**Comment by jackherizsmith** [comment]
How do we teach this alongside Git, potentially using VS Code's source control relates

**Comment by oliverjam** [comment]
We should probably just recommend applicants do this:
https://www.digitalocean.com/community/tutorials/a-linux-command-line-primer

It's Linux focused but should work on any Bash system. They have an interactive terminal embedded in the page so people don't even have to have their local env set up properly.

**Comment by oliverjam** [comment]
We now include the above DO resource in our pre-course material. We're also encouraging the cohort to get used to using their terminal for everything during this time
