### ISSUE TITLE
Move workshop content into Coursebook

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#297]
It would be much easier to manage the curriculum content from a central repo. This would help with maintenance (e.g. it's hard to even find all the workshops at the moment)—all the PRs would be in one place.

In combination with moving from Gitbook to our own website this would allow us to do more interesting stuff within workshops. For example styling solutions/hints/info callouts differently, maybe code blocks that you can actually run to see the result etc.

We'd have to keep the source files for each workshop as separate GitHub repos (so that they are clone-able). I imagine those repos would have READMEs just documenting how to run them.

**Comment by sofer** [comment]
@oliverjam is already working on this. He will continue working on it. Next step make a pr and share the new content.

**Comment by oliverjam** [comment]
I'll get a PR up and try to get it merged before the next circle. The new site is compatible with Gitbook so we can run them in parallel for a bit without having to make a decision.

**Comment by jackherizsmith** [comment]
Relates #316
