### ISSUE TITLE
Our introduction to testing

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#3]
We discussed how we might adapt our intro to testing at the last meeting. I presented my ideas for introducing the concept without any testing framework. I've created a [rough workshop](https://github.com/oliverjam/learn-testing/) for how this might look.

We liked a few things about this approach:

1. We can avoid introducing node and npm before Node week
1. Tests will run natively in the browser rather than node (so no awkward `module.exports` hacks)
1. It lets students "see behind the curtain" and hopefully demystify testing a bit
1. It will allow us to test more than just pure functions if we want

We also discussed not limiting ourselves to only testing the pure functions/app logic. Currently the Week 2 project has a ton of boilerplate to ensure students are building an app that is unit-testable. This is often a sticking point and people end up spending more time trying to understand the (unusual) structure rather than writing tests.

With browser-based testing we aren't so limited, so we can have them write tests for complete features, which will more closely match user stories. We discussed having them do pseudo-BDD, where we potentially give them boilerplate tests that match the user-stories that they have to fill out then make pass.

E.g.
```js
test("I can add a todo to the page", () => {
  const input = document.querySelector("input");
  input.value = "my todo"
  const button = document.querySelector("button");
  button.click();
  const todo = document.querySelector("li");
  equal(todo.textContent, "my todo"); 
})
```

Personally testing never clicked for me because unit testing and TDD feel so removed from user-facing features. TDD especially is (mostly) a development tool for solving problems. It wasn't until I started testing actual features as if I were a user that I really _got_ testing.

**Comment by arrested-developer** [comment]
This seems like a cool idea. I'd like to know more about how we build this up, what is introduced first etc. I think we need a roadmap of testing expectations throughout the course and how they build up. What are we expecting them to be able to do at the end?

**Comment by oliverjam** [comment]
This is fully my opinion, but I would say the point of testing (from an agile perspective at least) is "to verify the software fulfills the user stories". So I see this as the high-level testing LO of the course.

I pretty much agree with [Kent's testing trophy]() philosophy, where you have static analysis (a linter), a few unit tests, lots of integration tests and a few end-to-end tests.

I'd suggest there isn't enough difference between unit and integration testing to distinguish too much early on. Introducing testing concepts with basic math functions, but extending that to checking string values on the page etc. I don't think unit testing is useful enough or complex enough to have the first 5 weeks devoted to it 🤷‍♂.
