### ISSUE TITLE
Rename student projects

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#302]
We are moving away from calling members of the current cohort "students"

**Comment by oliverjam** [comment]
I guess they might end up being "Final projects" or something if TFB changes

**Comment by Albadylic** [comment]
"In-house projects" vs "Client Projects"?

**Comment by sofer** [comment]
@oliverjam to do a search for the word "student" and replace it with "developer" in this repo.

**Comment by jackherizsmith** [comment]
Classroom to be renamed The Developers' Studio

**Comment by sofer** [comment]
"Final" or "Tech for Better" project. Awaiting decision.

**Comment by Albadylic** [comment]
We call them 'in-house projects' and the Tech for Better project remains.
