### ISSUE TITLE
TfB build week 1 schedule tweak

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#307]
The [TfB build week 1 schedule](https://github.com/foundersandcoders/coursebook/blob/main/projects/tech-for-better/build-1.md) might need a tweak. The book says:

## Day 5

| Time    | Activity                        |
| ------- | ------------------------------- |
| 09:45   | Check-in                        |
| 10:00   | Code Review                     |
| 11:00   | Sprint Review                   |
| 12:00   | Presentation Prep               |

But there is no time for sprint planning. It looks like code reviews have been dropped for FAC20 and 10:00-12:00 is for both sprint planning and sprint review.

**Comment by jackherizsmith** [comment]
Yep we only noticed this this morning, I've fixed in the coursebook. Let's keep next circle to talk about code reviewing in tech for better

**Comment by jackherizsmith** [comment]
Live code reviewing to be added to schedule, required of project mentors
