### ISSUE TITLE
git & GitHub intro

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#311]
This is an important and confusing topic for new learners/FAC applicants

- What is git?
- What is GitHub? How is it related to git?
- How can we use VS Code to save our changes in git?
- How can we use VS Code to sync those pages to GitHub?
- How can we deploy HTML via GitHub Pages?

**Comment by jackherizsmith** [comment]
Relates #203

**Comment by oliverjam** [comment]
The workshop went pretty well. I presented [these slides](https://fac-slides.netlify.app/slides/intro-to-git/). I've also written up notes on Slack. Not sure the best way to keep track of these. I'm going to start adding these resources to the Coursebook I think
