### ISSUE TITLE
Self-organising study groups

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#317]
FAC20 are organising themselves into a study group 🎉 

[Here are the slides](https://docs.google.com/presentation/d/1rjelKgyO4h_L96lAqCwDz6MwF4JZUhMLZvK9_MKmwSk/edit?usp=sharing) from last time we tried this.

I have asked @jhart5 to document their processes, so that we can add it to the handbook.

**Comment by jackherizsmith** [comment]
Josh to report back to Dan on success of group
