### ISSUE TITLE
Digital literacy and study skills cheatsheet

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#321]
I don't know if we need to prepare a talk on digital literacy and study skills, but we need to have resources available for learners to read and for us to set as homework. This is a non-exhaustive list:
- touch typing
- using keyboard shortcuts
- effective use of search engines
- scheduling regular study time
- finding a study partner
- taking breaks (pomodoro)
- Creating your own flash cards (anki)

**Comment by Albadylic** [comment]
Cheatsheets & good practices:
- Look for help in the app you're using - e.g. what shortcuts are specific to VS code?

Gregor to make first draft of structure and articles for each bulletpoint

**Comment by Albadylic** [comment]
First draft:

https://www.notion.so/foundersandcoders/Digital-literacy-and-Study-Skills-Cheat-sheet-7d9bca377c8841569d953a3542e1d65d

**Comment by sofer** [comment]
@oliverjam has reviewed. @gregor to move to handbook.
