### ISSUE TITLE
Team selection in a 12-week programme

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#322]
Given the continuing challenges of selecting teams in the latter part of the course, perhaps we could consider pre-selecting all the teams for the entire length of the course at the beginning of Week 1. Teams stay together for a minimum of 2 weeks before reforming and then 3 weeks for the final project.

**Comment by sofer** [comment]
AGREED, but we also need to make sure that no team is majority male.

To do: ensure this happens for FAC21 and make sure that we do it before the start of FAC21 and publish the teams in advance.

**Comment by Albadylic** [comment]
@Albadylic to update CF documentation

**Comment by jackherizsmith** [comment]
https://jackherizsmith.github.io/team-maker/

**Comment by Oliversw** [comment]
Currently reflected in the pre-determined teams for FAC21: https://github.com/fac21/cohort/blob/main/pairs-and-teams/teams.md

**Comment by oliverjam** [comment]
We should try and automate generating this (and the rest of the facxx org) for each new cohort to save the CF a bunch of time

**Comment by jackherizsmith** [comment]
Is there anything the team maker is missing? I'm happy to update it where it needs improvement. At the moment it generates markdown for 16 students into 8 weeks of teams and rotating workshop pairs, so the time input should be limited to putting in names and pasting to GitHub.
