### ISSUE TITLE
Talk in Week 1 on what to expect from mentors

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#325]
We do not adequately explain to students the different sorts of mentors and what can be expected of them and underlining that they are mostly recent graduates:
- Week mentors
- Pastoral care mentors
- Project mentors
- Role mentors
- Employment mentors
- Coaches

**Comment by sofer** [comment]
It also needs to be a page in the handbook.

**Comment by Albadylic** [comment]
First draft [here](https://www.notion.so/foundersandcoders/Mentor-Roles-9c58152c6808430dabe5800481e16496).
