### ISSUE TITLE
Final project technical guidance

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#329]
If we're merging the Student Project and TFB project into a single "Final Project" we should provide more technical guidance at the start.

There are lots of things that are impossible to do in the previous 2 day projects, and this is their one chance to practice "real world" stuff on a larger project.

Things we want to encourage:
1. Dev env setup (Prettier, ESLint, precommit hooks etc)
1. Solid devops (staging/test/prod envs #328, CI running tests)
1. Practice with technologies they already tried (rather than using a bunch of new stuff—this may be controversial)

**Comment by oliverjam** [comment]
This would probably be covered in the new Week 9 suggested in https://github.com/foundersandcoders/coursebook/issues/288#issuecomment-746578159

**Comment by jackherizsmith** [comment]
Also potentially being more explicit about building a frontend first with dummy data, then a backend after. Or at least, the advantages and disadvantages. FAC19 all built backends first. We caught FAC20 and so they did frontend first, but weren't quite sure why.

**Comment by oliverjam** [comment]
Thanks Jack, definitely good to bear in mind. We'll track this in the Week 9 issue
