### ISSUE TITLE
Precourse review

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#344]
Including apprentice interview prep.

**Comment by oliverjam** [comment]
I just did a quick overview of the current recommendations. There's definitely some stuff to get rid of—including a DOM tutorial from 2012!

So I don't forget/lose my thoughts:

- Remove ancient DOM tutorial
- Tbh remove all the DOM stuff and start again (except maybe the MDN one)
- Replace old Markdown tutorial with [official GH intro](https://guides.github.com/features/mastering-markdown/)
- Change project to a Pomodoro timer
- Swap Codecademy SQL to Execute Program

**Comment by Albadylic** [comment]
Split the cohort into tutor groups. 

On _Friday_, deliver a short presentation on the topic for the week (HTML, CSS, JS, DOM). We record this and provide the recording to the cohort. 

On _Tuesday_ each tutor group meets with their tutor to discuss the material. 

Each week covers Git,Github, Cmd Line and Markdown.

**Comment by oliverjam** [comment]
We delivered a revamped 4 week pre-course to FAC21 that seems to have gone pretty well. Each week is documented in the new Learn platform, e.g. https://learn.foundersandcoders.com/course/syllabus/precourse-1/schedule/
