### ISSUE TITLE
Final projects

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#349]
Problems:
1. We only have time for one project
1. No Student Project means no safe place to make mistakes/learn without much pressure
1. TFB projects have external POs who want real MVPs

Solution:
Run a hybrid of Student/TFB projects. We choose the project ideas (with recommended APIs etc) and pick internal POs from the community. This reduces the pressure of a proper TFB project but still gives them the opportunity to work in a "real team". Controlling the idea reduces the risk of people picking their own wildly out-of-scope dream app ideas and getting stuck/failing to learn much.

**Comment by Albadylic** [comment]
Quick update from @Oliversw and I's discussion in our catch-up this week:

Filling the role of Product Owner on a project that isn't your own seems counter-intuitive. Feigning investment in an idea we've come up with seems a lot to ask of alumni and will never truly emulate the passion of an external PO. The most valuable learnings from Product Owners are when they bring challenges to the table (lack of availability, unclear communication, high expectations). Having three mentors (project, role and PO) per person seems like it'll be too many variables to have a clear sense of the distinct roles. For these reasons we feel that we shouldn't try the internal PO's for this project.

Coming up with ideas should be done by the core-team prior to the projects beginning. Whether we give a theme for them to riff off of, a brief, or a problem statement is to be decided.

**Comment by Albadylic** [comment]
- Teams focused on Technology they'd like to learn, how that could be tied together into a platform, then how that platform could serve a user group. Given the time constraints we feel this went surpripsingly well.
- Some folks mentioned that they had a hard time choosing a platform in a short window (~30 mins)
- Asking them to think of an idea first seems to be an easier approach for the developers but can often result in them thinking of technology orthogonal to what they've learnt
- We could give them a chance (30 mins) a week before to think about which user group they might like to serve and how. Then they can decide on tech in the next week, perhaps they follow the same process the following Monday. 
- Previously creating the issues, voting and deciding was a really time intensive and demanding process

@Albadylic to update the schedule for Week 9

**Comment by Albadylic** [comment]
@Albadylic to revisit for FAC22's final projects

**Comment by Albadylic** [comment]
We have two projects again - closing this issue.
