### ISSUE TITLE
Cultivating a habit of learning

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#360]
This is something that has been bothering me for some time and that I am pretty sure that for many people we are just getting plain wrong. 

Historically, we have not been good at cultivating the simple habits of individual learning that are likely to be the difference between a so-so developer in danger of getting marginalised in a [bullshit job](https://en.wikipedia.org/wiki/Bullshit_Jobs) and somebody who is capable of developing real autonomy in their working lives.

I realise that this is a departure from our broad advice to learners to down tools when they are not in the classroom, but I just don't think that is good enough or even very responsible. The FAC students who excel on the course almost all share in common some habits of learning that they nurture outside the classroom and to pretend otherwise is to do everyone else a disservice.

The introduction of a structured part-time programme gives us the opportunity to do this properly for the first time before we go full-time. I agree that developing these habits while also doing FAC full-time is going to be a challenge for many people.

The copy below is my first take on the advice that we should be giving to FAC21.

> The most important thing that you need to cultivate as a successful developer: a habit of regular daily learning. Use the pre-course to do that. Then keep it up throughout your time with us and beyond. This is our strong recommendation to you:
> 
> 1. Set aside two (25-minute) pomodoro sessions every day for learning, one at the start of your working day and one at the end.
> 2. During your start-the-day session, focus on active problem solving, through a platform like e.g. [Codewars](https://www.codewars.com/).
> 3. During you end-the-day session, focus on reading and taking notes and then saving your notes in a platform like [Anki](https://apps.ankiweb.net/), so you can turn reading into an active learning process.
> 4. More than anything, turn this into a habit that you do every working day, so that you don't have to will yourself to do it. Don't miss days. Don't go over your alloted time. 25 minutes first thing; 25 minutes before you down tools each day.

**Comment by Oliversw** [comment]
After talking about this we all agreed that it is a good idea. It needs to be structured in a way that removes mental overhead for the developers, particularly while they're trying to build a habit.

Ideally it would begin at the start of the precourse but we agreed that for FAC21 it will be introduced at the next group workshop (tomorrow). To begin with we will suggest to focus on ExecuteProgram, with the potential of suggesting more resources in the coming weeks.

We also talked about the importance of reading articles and books in addition to practicing coding. Twitter was suggested as a potential source of articles but also distraction, while RSS feeds seem a little better. Oli spoke about collecting a few different articles/resources that could be useful for the developers to share with them.

**Comment by sofer** [comment]
@sofer make a pr in handbook.

**Comment by oliverjam** [comment]
I delivered [these slides](https://fac-slides.netlify.app/slides/precourse-4/) to FAC21 as part of the pre-course, including recommendations on building their learning habits every day.
