### ISSUE TITLE
Clarify consequences to repeated rules violations

### ISSUE THREAD

**Issue by Oliversw** [foundersandcoders/coursebook#365]
Going through the first few talks in week 1 I realized that we have a number of sets of rules in multiple places, which is getting a bit confusing. 

We have the [code of conduct](https://www.foundersandcoders.com/code-of-conduct/) on the website, [course rules](https://github.com/foundersandcoders/coursebook/blob/main/src/course/handbook/course-rules.md) in the coursebook, and [cohort expectations](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/cohort-code-of-conduct.md) of which the explanation is in master reference but the outcome is saved in the cohort-specific repo.

After speaking to Gregor I think that a simplified solution would be to keep the code of conduct and the cohort expectations. The code of conduct would be for absolute rules, while the course expectations would remain more about being polite and working together better. Some of the course rules feel a bit redundant, and have crossover with the expectations and other documents.

**Comment by Oliversw** [comment]
https://github.com/foundersandcoders/coursebook/compare/recurse-rules

No taking screenshots of people - some people might not want that

What is the consequence for non code of conduct breaking rule breaks - people should be 

Spoke about this today in the FAC21 Circle. Agreed that the course rules as they stand should be removed, but there are social rules that should still be communicated. @oliverjam agreed to write up some new rules which are in PR #366 

Also spoke about adding rules about not taking screenshots of zoom (which Oli has included in PR):
Do not take screenshots or photos of the classroom. Some people have not given photo permissions - you MUST ask explicit consent before taking or sharing a photo or screenshot.
- What happens when someone misbehaves or says something out of line in a group. Who is going to address that? What happens after that? If you feel uncomfortable with something someone has said and don't feel comfortable in addressing it directly you can bring it up with staff and we will seek to help you find a resolution. We'd like everyone to feel comfortable in addressing these issues.

Also importantly we still need to define what the consequences are for breaking social rules.

**Comment by oliverjam** [comment]
That's a good point—I only mentioned what action to take. We should probably have a policy about repeated violations being escalated (as you lose the good faith defence if you persist in breaking rules after being told)
