### ISSUE TITLE
Revisit reading week checklist

### ISSUE THREAD

**Issue by Oliversw** [foundersandcoders/coursebook#368]
The [reading week checklist](https://hackmd.io/@3h2qEDKEQXSZK4l2wloSMg/SJrDiJyBB) (#265) is a nice resource but we might need to update it for the current cohort, since reading weeks are coming after week 3.

**Comment by Albadylic** [comment]
I think this is our most recent iteration of reading week guidance:

https://github.com/foundersandcoders/coursebook/tree/main/src/course/syllabus/reading-week

**Comment by oliverjam** [comment]
## Circle discussion notes

There will be a 2 week break, so we should encourage them to take the first week as an actual break where they don't try and do any code.

I don't think we've recommended that checklist in a while (it was written for the middle east campuses originally). @Albadylic just linked the most up-to-date guidance above (see #120 for previous discussion)

**Comment by oliverjam** [comment]
Sorry I didn't link the commit but I added an updated checklist to the coursebook in #403
