### ISSUE TITLE
Move live code review to before group code review

### ISSUE THREAD

**Issue by Oliversw** [foundersandcoders/coursebook#381]
At least in week 1 this might help to frame how to do it and how to avoid common mistakes. Not sure if this is worth doing for all weeks but I think it would be good in week 1 at least

**Comment by oliverjam** [comment]
Yeah I think you're right. Some of the week 1 code review ends up not really adding much because they have no idea what they're supposed to be doing yet.

**Comment by oliverjam** [comment]
Closed in #386
