### ISSUE TITLE
Final project: order of play

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#406]
In case we want to give teams leeway in the order in which to tackle the front and back ends in the final project, https://retool.com/api-generator/ might be a nice tool for allowing them to tackle the frontend before the backend is up and running.

**Comment by oliverjam** [comment]
I'll write a little intro to building their projects frontend-first with mock data in a JSON file. That way they can avoid all the faff of setting up Postgres for the first week at least and focus on solving their user problem with an MVP

**Comment by Albadylic** [comment]
[This slide deck](https://hackmd.io/Bqep1Gv0QU-AvA4AMzV-Vg) is presented before build starts.

**Comment by oliverjam** [comment]
**Result**: I shared [a HackMD](https://hackmd.io/h9409mb6SM6eR4MqvvQpJA) explaining how to build frontend first by mocking the DB using JSON files. It seems like nobody followed it though, and every team ended up spending their whole first week stuck on backend and didn't have much to user-test/present.
**Action**: incorporate this into the intro presentation for builds, _and_ make it a requirement for week 1 presentations. "You must have a usable frontend to present by Friday etc"
