### ISSUE TITLE
Post-course learning: one peer learning day each week.

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#426]
After the course ends, one day each week we could offer a peer learning day, which could take the form of a [one-day project](../blob/main/src/course/projects/one-day-projects.md) or [CS50](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x) or something else. It looks like there will be interest in this from some of our apprentice employers, but there is every reason to make this open to everyone while they are job searching and working on Tech for Better projects.

**Comment by sofer** [comment]
I am leaning towards a format that looks something like a single project in teams of 2 over a 3 or 4-week period with clearly-stated learning outcomes (with projects and outcomes agreed and defined in advance by each team in consultation with a mentor) and with presentations at the end of each day. The benefits of this approach:
- We can keep apprentices together and make it relevant for employers;
- For job seekers, the multi-week approach means this can be a substantial side project for their CV;
- Learning outcomes agreed in advance ensure that the focus is on learning or consolidating appropriate skills;
- Keeping the teams small means a focus on paired working and relevant learning for each person;
- Presentations ensure that the whole group is keeping each other accountable;
- The focus on projects means that the responsibility for learning falls on each pair, not on mentors, which is where it belongs at this stage in people's learning.

**Comment by sofer** [comment]
Alternatively, it might be more useful to have people working solo, and only pairing up to code review. After 12 weeks of working in teams, it might be helpful for their professional to spend some time working on their own.

**Comment by sofer** [comment]
Agreed at circle. On Wednesdays. @Oliversw to add to SGC this week. @sofer to talk to apprentice employers about it.

**Comment by sofer** [comment]
Adding back the `next-circle` label as we need to bin this down before the end of the course. Conversations are ongoing with employers, but we also want to make something available to the rest of the cohort. We have also had offers of workshops (e.g. Elm and Python/Flask).

**Comment by Albadylic** [comment]
[This guidance on one day projects](https://learn.foundersandcoders.com/course/handbook/one-day-projects/) might be a good starting point

**Comment by sofer** [comment]
@Albadylic @oliverjam Follow-up call tomorrow (Thursday). 

Starting-point for discussion:
- Make Wednesdays our learning days
- Start on Wednesday 30th
- Start with an initial 3/4-week curriculum using a mixture of structured learning materials on topics like Svelte, D3 or AWS followed by mini-projects (am: make as much progress as you can working in pairs on a tutorial; pm: work on a mini-project in the same pairs and present back at the end of the day?)
- Review how it's going after the first couple of weeks and put together a follow-up curriculum, based on how the first couple of weeks have gone.

**Comment by sofer** [comment]
@oliverjam a request has come in for learning Docker deployment on AWS.

**Comment by oliverjam** [comment]
Hmm okay, maybe Docker + AWS is enough without the complication of TypeScript (for the first session at least)

**Comment by oliverjam** [comment]
God I hate AWS 😓. Doing a bunch of research into deploying Docker containers and it is a mess. I don't even know if I could _do_ it, let alone distill the process into something beginners will understand. It doesn't look like we could use the free tier either, so that's a whole other consideration.

**Comment by sofer** [comment]
@oliverjam and I met yesterday and agreed to start (probably) on Tuesday 6th July with a Docker/AWS session. Other sessions will be scheduled as we go.

**Comment by sofer** [comment]
Some old Docker learning links https://hackmd.io/3fgyQ9knQr-z7EyNAZo5yA

**Comment by oliverjam** [comment]
Given there's limited time before next week we'll do Svelte first. I'm more familiar with it and there are great official learning resources. I'll put something together for Docker the week after. I'll be on holiday that week so @Albadylic might be running the session (or we could delay a week)

**Comment by oliverjam** [comment]
We've had some feedback from the apprentices based on the first few sessions. To summarise: they only get 1 day per week off work for learning. Spending that day learning a totally new topic that they won't actually be using isn't the best use of this limited time. 1 day is also not enough time to really learn much about a totally new topic.

Going forward we're going to try making these days more of an open-ended "study hall" type thing. Graduates can bring whatever problem/technology they'd like to work on, and hopefully get help from me/each other. We also discussed potentially paying for courses etc if they give us advance warning of a topic.

**Comment by oliverjam** [comment]
These appear to have run their course for FAC21 now. We don't have a full-time finishing so don't need to worry about these until the end of FAC22.
