### ISSUE TITLE
React week - Anni's talk on Tuesday

### ISSUE THREAD

**Issue by Oliversw** [foundersandcoders/coursebook#427]
Anni will have her last talk on Tuesday May 18 which is during React week, 11am. Putting it here to give Oli more of a heads up when the schedule is being re-done. If 11am is a bit too disruptive to workshops it is probably possible to move the talk to 10am given that we don't have research presentations at that point.

**Comment by oliverjam** [comment]
Having it first thing would definitely be easier to manage. The React intro workshop is pretty long so would be good not to have a single hour split at the start of the day. Possibly better for Anni too in her timezone? 😅

**Comment by Oliversw** [comment]
Perfect! I'll send her an email now to propose a 10-11:30am talk :)

**Comment by Oliversw** [comment]
Anni is confirmed for 10:00-11:30am on Tuesday May 18th :)

**Comment by Oliversw** [comment]
Anni messaged and asked to be moved to another day because of a conflict. I spoke with Oli in the curriculum channel and then moved Anni's talk to 10:00-11:30am on Tuesday May 20th. It's not ideal but hopefully it will not be too disruptive for the teams to begin their project week on the Tuesday afternoon during the usual speaker slot.

**Comment by oliverjam** [comment]
Tbh from memory the workshops on Tue tend to run long so they could just keep going until 6
