### ISSUE TITLE
Interview preparation (pre-apprenticeship) programme

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#432]
Just a marker to remind us to start thinking about this seriously.

**Comment by oliverjam** [comment]
@Oliversw to write a quick Airtable form asking about FAC21's pre-course so we can judge how intense/time-consuming this can be.

**Comment by sofer** [comment]
First draft of some potential elements of the programme:
- something like the [pre-course](https://learn.foundersandcoders.com/course/syllabus/precourse-1/schedule/)
- weekly Q&A sessions with employers
- weekly tech interview practice in groups of 4
- weekly tutorial in groups of 4
- weekly peer-led pairing or small-group sessions
- CV / LinkedIn / employment prep sessions at some point
- Daily study commitment 1: codewars or executeprogram or something similar
- Daily study commitment 2: something like [180 websites](https://jenniferdewalt.com/)

The commitment we have made to the DfE is:

Hours | Activity
-- | --
3  | workshops
3  | small-group   tutorials
10+ | Peer-led   learning and individual study

It may make sense to run sessions 4-6 or 5-7pm three days/week. The other possibility is two 3-hour sessions each week, 4-7pm.

**Comment by sofer** [comment]
Provisionally agreed:
- 2 x 3-hour sessions;
- 6-9pm, perhaps;
- Back-to-back on Wed/Thurs, perhaps.

Refer to general circle.

**Comment by Oliversw** [comment]
[Link to the precourse feedback from FAC21](https://airtable.com/tblcGPOU8anbBHb2v/viwDFG6JHvjYyyE35?blocks=hide)
