### ISSUE TITLE
Scheduling time for testing and estimation

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#452]
The project teams are struggling with finding time to do estimation and testing. Perhaps we ought to schedule 30 mins on Wednesday at 2pm to do story estimation and 30 mins on Thursday at 10am to set up tests. 

Scheduling time may be the only way that we can ensure some attention is paid to these two hugely important tasks (arguably the two most important skills to be learnt at FAC) and making the time very short means that it won't take up an inordinate amount of project time. Just getting into the habit of doing these things at about the right time in the project, even if it means only very rough estimating and writing a couple of tests, is going to be worth it.

**Comment by sofer** [comment]
Make Wednesday more structured:
- decide on scope
- set up repo
- write user stories
- do software estimation
- set up tests
- set up production environment

Trial it for next week and then use it for FAC22

**Comment by oliverjam** [comment]
@oliverjam  to put all this stuff into the schedule for Build Week 1 Monday
