### ISSUE TITLE
Tech Spikes in Design Week

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#461]
We have tech spikes scheduled on Thursday afternoon.

We didn't have any particular guidance in place for what to cover, I think in FAC20 we asked them to consult with their mentor on what to cover.

They'll do tech spikes in their role groups.

https://learn.foundersandcoders.com/course/syllabus/final-project/spikes/

Would we like to give some more specific guidance?

**Comment by oliverjam** [comment]
I think this worked okay for FAC20, so I'm happy to leave it as is

**Comment by oliverjam** [comment]
Circle discussion: we'll keep it roughly as is. Clarify that they can work in pairs if they want to investigate different things (but not alone). The DevOps spike should recommend looking into staging environments to fulfill #328

- DevOps: staging env (e.g. Vercel/Netlify already auto-deploy branch previews, but they'll need to set up a separate staging DB)
- UX: styling methodologies
- QA: testing in GitHub Action CI
- Scrum: 🤷 

@Albadylic to update the Coursebook document
