### ISSUE TITLE
Knowledge, Skills, Behaviours: prep for EPA

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#465]
we [made a start on this](https://www.notion.so/foundersandcoders/Software-Developer-Standard-10bafc310864472fbefb8b331023d5d2), but we now need to return to it and work out how we are going to best use the time that we still have available with the apprentices (and it's [quite a bit of time](https://www.notion.so/foundersandcoders/Off-the-job-training-time-37512df7edc24cceb0d9cd54658a0dac)), to ensure that we have covered all the required material well in advance of the end-point assessment and in a way that is relevant and useful to both apprentices and employers.

**Comment by sofer** [comment]
Giving this a bump.  Sequentially, it's the final part of the curriculum. End-point assessments will be starting from April 2022. Preparation with FAC21 needs to begin early in the new year. Planning needs to start soon.

**Comment by oliverjam** [comment]
We need to ensure we are preparing our apprentices for their end-point assessments. This is something ofsted will inspect us on.

1. Look over the documentation for assessments/talk to the British Computer Society
2. Talk to employers about these requirements (e.g. if the apprentice is using a work project the assessors will need access to the code)
3. Set up workshops/resources for apprentices to inform that what the expectations are around assessments

@oliverjam & @sofer to schedule a 30 minutes session weekly from October 11th to keep up momentum on this.
