### ISSUE TITLE
Curated list of tech interview resources

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#466]
Previously mentioned (briefly) here https://github.com/foundersandcoders/coursebook/issues/109#issuecomment-621090321, but one of us could potentially use some time to try out and review a list of online resources for tech interviews.

Here's another one. https://app.geektastic.com/

**Comment by Oliversw** [comment]
I'm happy to take this on @sofer. Is there somewhere in particular that you would imagine this being stored?

**Comment by sofer** [comment]
I'll make an initial list of resources to discuss next week.

**Comment by sofer** [comment]
This is still on my list.

**Comment by oliverjam** [comment]
Potentially mock interviews/whiteboard sessions/code challenges (like FAC18's Employment Day) would be valuable. Could ask alumni who do hiring/off-cycle employment partners to help out. Maybe this would have to be distributed a bit to fit into the part-time nature of Term 2
