### ISSUE TITLE
Rework alumni/employer mentor roles document in handbook

### ISSUE THREAD

**Issue by Oliversw** [foundersandcoders/coursebook#469]
I'm not sure whether it is because we're remote, they're doing more complex projects, or they are just used to asking for help more, but I have found that FAC21 has needed more help from project/role mentors that I was expecting. Even with that they have still expressed not knowing where to find help sometimes when their mentors are busy at work. Generally I think that this is probably healthy because it is closer to real life, but I think it is worth discussing if it is worth trying to find more mentors to be around for bug fixes, or if it is okay to leave them to get through it as best they can. 

This will be useful to discuss in order to communicate both the mentors and the cohort what to expect, because I don't think I communicated effectively to those that volunteered, and sometimes it feels like the cohort expects them to be available every day.

**Comment by oliverjam** [comment]
Yeah maybe calling them "mentors" gave the cohort the expectation that they were full-time always available mentors like in the first 8/9 weeks?

**Comment by oliverjam** [comment]
## Circle discussion

- Project mentors are for general advice on architecture, technologies etc, **not** debugging day-to-day errors
- Team should schedule specific slots to talk with project mentors
- Teams are responsible for fixing their own bugs/errors using all the resources available to them
   - Resources includes SO/other online stuff, but also our community channels (e.g. #facoverflow)

**Comment by reubengt** [comment]
I'm guessing this was added back to be documented in the handbook.
I think we can rework the [what to expect from your mentors](https://learn.foundersandcoders.com/course/handbook/mentor-roles/) document in the handbook, and also our communication to potential mentors to better reflect the comments above.

Below is what im sending to FAC24 project mentors
```
We're looking for project mentors for FAC24's final projects. This is an exciting opportunity to get involved in apprentice training before they join you for full-time work!

Depending on your availability - this would involve
- Giving advice on technical choices
- Reviewing project scope
- A code review halfway through the sprint
- A checkin call with the project team

This would be a time commitment of roughly four hours spread across two weeks.

The apprentices are expected to be quite independent during final projects, and are responsible for reaching out to you. That being said - at the start of the project, do let them know what your availability is.

```

**Comment by ByteSizedIT** [comment]
Current, updated documentation in handbook, for confirmation: https://learn.foundersandcoders.com/course/handbook/mentor-roles/
