### ISSUE TITLE
Pre-apprenticeship structure

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#478]
Structure the weeks into pairs based on topics (CSS / Git & Teamwork / Promises and Fetch / Testing ). These will cover the first 3 weeks of the FT curriculum and current precourse. [Rough draft on Notion](https://www.notion.so/foundersandcoders/Wednesday-3e224f761d5f447da2cdafe5f61ae29d). They'll still cover Execute Program and have additional homework.

Each pair of weeks will have a longer project which they start in the first week. The second week gives more content so they can revisit and add to their current project. Giving them some perspective on refactoring.

The CSS project will be done individually and the following ones in pairs. Each pair will be given a set of user stories to focus on and be asked to split these between them based on time estimates (initially from us, and then self-estimated). This will give them a chance to do some asynchronous Git and Code Review. 

Final weeks will be a final larger project with less new content as they will likely be interviewing.

Relates to #473

**Comment by Albadylic** [comment]
- Estimating time for each workshop and how much time should be spent each week on each activity (@Albadylic )

- Mapping the post-workshop discussion from main course to an asynchronous method (e.g. drop-ins or discord discussions)
- The workshops weren't written with whole group discussions in mind, it might not be problematic to miss out on these
- Ask them to schedule discussions in a group of 3 and generate a set of questions they have post-workshop
- Mapping the pairs for workshops, projects and discussion groups (@oliverjam )

**Comment by Albadylic** [comment]
- Generally the programme is going well
- The only negative so far is that folks have felt there is too much to do
- It doesn't seem anyone is behind or missing out on anything
- They have been working well on their paired project and merging each others PR's
- Focus is on the longer term projects and our workshops rather than EP or JS30
- Execute Program and Khan academy could be given earlier

**Comment by sofer** [comment]
From Gregor:
- working in pairs on projects
- still concerned about the amount of work we are giving them
- maybe go easier on execute programme
- everyone seems to be doing at least the minimum.
- merging of each others' pr's seems to be going well

@oliverjam to write guidance on how to approach workshops, ask for help, not to get stuck, use Execute Programme, etc.

**Comment by sofer** [comment]
@sofer also to do a quick intro to how to hack Execute Programme.

**Comment by Albadylic** [comment]
Relates to #504 - revisiting the curriculum
