### ISSUE TITLE
Order of delivery of Execute Program courses

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#491]
Suggested order of delivery:
- JavaScript Arrays (48 lessons, 24 entries in cheatsheet)
- Regular Expressions (30 lessons, 16 entries in cheatsheet)
- Modern JavaScript (44 lessons, 44 entries in cheatsheet)
- JavaScript Concurrency (33 lessons, 27 entries in cheatsheet)
- SQL (35 lessons, 30 entries in cheatsheet)
- TypeScript (69 lessons, 44 entries in cheatsheet)

It turns out that some of FAC22 have been doing Modern JavaScript before JavaScript Arrays, which may not be the right order. For most people, it is a significantly more challenging course. The order above is a suggested running order and we could perhaps introduce a new course at 2-week intervals. Regular expressions is earlier, because it is significantly shorter and conceptually easier than the later JS courses.

**Comment by sofer** [comment]
See e.g. https://twitter.com/cosmicindustry/status/1416708030075392001 and https://twitter.com/cosmicindustry/status/1416485039093821440

**Comment by sofer** [comment]
Discussed last week and assigned (As I remember) to @Albadylic to update the Skills Bootcamp curriculum.

**Comment by Albadylic** [comment]
Relates to #504
