### ISSUE TITLE
Replace external requirements with our own

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#492]
Khan Academy offers us the opportunity to assess the progress of learners in a more fine-grained way than platforms like, say, freeCodeCamp. Their [Computing Curriculum](https://www.khanacademy.org/computing) looks good and is based around JavaScript.

There is a case for starting our learners off with [Computer programming](https://www.khanacademy.org/computing/computer-programming) (up to _HTML/JS: Making webpages interactive_) as well as [Computers and the Internet](https://www.khanacademy.org/computing/computers-and-internet). 

We are currently trialling [Algorithms](https://www.khanacademy.org/computing/computer-science/algorithms) with FAC22 (see #485). They are finding it challenging, but in terms of difficulty, it is probably at a level suitable for preparing for entry to the job market. They have also been set optional homework of [Get Ready for Algebra 1](https://www.khanacademy.org/math/get-ready-for-algebra-i), as a remedial intro to algebra.

**Comment by oliverjam** [comment]
I'll take a look through some of the intro material to see how it compares to fCC. We would like to replace our fCC requirement with this if possible

**Comment by sofer** [comment]
This [comparative report of Khan Academy and freeCodeCamp](https://github.com/foundersandcoders/coursebook/files/6911205/comparative.report.of.Khan.Academy.and.freeCodeCamp.docx) was done by a Year 11 student on work experience back in 2019. She clearly preferred fCC.  Two other work experiencers were set the same task in the same week, and although they didn't write up their findings, they preferred Khan Academy, because they found it easier to follow.

**Comment by oliverjam** [comment]
1. @Albadylic to share projects with @oliverjam, then we'll start running them. We have enough to reach the end of this term
2. Stackblitz is amazing ✨ 
3. Not done yet but on my list. Need to nail down granular learning outcomes to make sure we cover everything

**Comment by Albadylic** [comment]
Realistically, we should aim for FAC25.

For FAC24, we can bring more practical challenges in as part of the daily challenge curriculum. This is a halfway to 60 mini-projects.

Make the challenges more tangible (e.g. filter out the email address duplicates). See the outputs on an HTML Page. 

There's benefit to being reactive to the pace of the cohort. We might prefer to only plan two weeks at a time rather than 12. 

Can we set up a GitHub repo which we push challenges to each week.

**Comment by Albadylic** [comment]
For Term 1 for FAC24, we'll keep the current requirements but with more structure to Daily Challenges cycle and move towards integrating these with developing websites. The algorithmic parts of challenges can be much quicker to complete than DOM challenges. 

Restructuring will be our goal for FAC25 and phasing out cohort will be our goal for FAC26. 

Working out how to effectively measure the challenges being completed will be important to this cycle. e.g. submitting on airtable or posting to GitHub

**Comment by oliverjam** [comment]
Discuss dropping Codewars either partly or entirely next week when @yvonne-liu is back

**Comment by oliverjam** [comment]
Outcome of circle discussion:

1. Drop Codewars
2. Make "Daily Challenges" more like "Daily Prompts"
   - Include some HTML/CSS stuff as well as JS ("use a CSS transition to make a link hover style")
3. Remove Solutions channel since these should now go on GitHub for us to track
   - This will hopefully stop people getting overwhelmed/put off looking at everyone else's work
4. (after Week 5's GH workshop) start posting Weekly Challenges incorporating HTML/CSS/JS/DOM

**Comment by Albadylic** [comment]
Something like this:

| Week | Topic | Prompts |
| :---:| :---:| :---:| 
| 1 - 4 | Functions, solving problems, DOM, arrays | See Discord| 
| 5 | GitHub | Create an empty repo on GitHub; Add HTML, CSS and JS files locally; Push these to GitHub; Deploy the repository; Push the content of your tribute page to GitHub using git flow | 
| 6 | Flexbox | Create a project gallery using Flex (making use of `justify-content`, `align-items`, `flex-wrap` etc.)|
| 7 | Image Carousel | Create a similar project that uses user input and a timer - e.g. [tortoise racer](https://github.com/Albadylic/tortoise-race) |
| 8 | Objects | Some tricky challenges from the previous daily challenges - upload solutions to GitHub |
| 9 | Building your website| Build a website which tells us about yourself and links to your other projects. | 
| 10 | Debugging your website | Code review your own website - make a note of learnings |

**Comment by Albadylic** [comment]
@Albadylic to add the prompts to the coursebook

**Comment by sofer** [comment]
Also, we discussed a possible re-ordering of the topics. In particular, moving the website build before flexbox. And perhaps introducing the idea of making issues before writing code as a way to encourage good habits early.
