### ISSUE TITLE
Study skills guide

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#498]
See #https://github.com/foundersandcoders/coursebook/issues/478#issuecomment-888203608

**Comment by sofer** [comment]
Bump.

**Comment by oliverjam** [comment]
I don't think I should prioritise this before I go, so I'm going to unassign and leave it in the backlog

**Comment by ivanmauricio** [comment]
we haven't made any progress on this for over a year. it's not clear whether everybody needs this as everyone has different learning styles. so we've decided to close it and if the need arises we will open up a new one.
