### ISSUE TITLE
Inclusive language guide

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#502]
We have lots of external people come into our space to speak to cohorts (e.g. employers). We also have partners sometimes want to host events with/"in partnership with" us. We need a guide to help our partners embody our values and have nice, safe interactions with our cohort members.

**Comment by Albadylic** [comment]
I've written a first draft of this, ready for review.

**Comment by Albadylic** [comment]
Reviewed, @Albadylic to redraft before final approval and bringing into use.

**Comment by Albadylic** [comment]
The final actions here:
- [ ] make a last couple of changes, suggest by Julia
- [ ] publish on our website
