### ISSUE TITLE
5 short talks on agile development and product management

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#515]
These are all pretty short, around 15 mins each. Are we still using them?

1. [A quick intro to managing software projects](https://hackmd.io/@fac/S1wGfV2M8#/)
2. [Issue management and estimation](https://hackmd.io/@fac/B1AL4V3ML#/)
3. [The Design Sprint](https://hackmd.io/@fac/rySEBaUq8)
4. [The Build Sprint](https://hackmd.io/@fac/S1ZTP6UcI#/)
5. [A quick intro to product management](https://hackmd.io/@fac/BkJLkLxnr#/)

**Comment by sofer** [comment]
@Albadylic apropos this week's circle discussion, it would be great to have time to include a revision of the issue management and estimation slides next week. In particular, make sure everyone reports on estimated vs actual velocity in their presentations in Week 2.

**Comment by Albadylic** [comment]
Squeezing these into the pre-apprenticeship may be a bridge too far. We did this for FAC22 and recapped them in the full-time programme. 

Introduce the projects and elements of these talks (estimating, user stories, opening issues, relating issues) in a lighterweight sense in the pre-apprenticeship so they can work asynchronously together. @oliverjam to make a couple of slides to introduce these. 

Introduce talks 1 and 2 in Weeks 1 and 2 of the full-time programme. @Albadylic to find a gap for each in the curriculum.
