### ISSUE TITLE
Bank holiday -> apprentice induction day during Build Sprint 1 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#526]
We have a [bank holiday scheduled during Build Sprint 1](https://learn.foundersandcoders.com/course/syllabus/apprenticeship/final-project/build-1/).

I suggest turning this into an optional induction day, perhaps on a Tuesday or Thursday, so that employers can optionally have their apprentice join them in person for a day.

For unapprenticed learners, it could be used for job searching.

This issue has been prompted by a request from one of our employers.

**Comment by Albadylic** [comment]
Thanks. I'll raise a PR for the weeks and we can discuss this issue at CC next week. Ahead of that, could you get a sense from the other employers if there'd be appetite for this?

I'd be happy to go ahead but if it's only of interest to one employer we may like to rethink what we do for the whole cohort.

**Comment by sofer** [comment]
I have spoken to employers. Just awaiting #527
