### ISSUE TITLE
More README structure for longer projects

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#531]
The [new Software developer apprenticeship standard](https://www.instituteforapprenticeships.org/apprenticeship-standards/software-developer-v1-1) has a well-defined assessment plan, which requires a 4,000-word project report, which _"must include the following sections"_:

- introduction
- the scope of the project
- project plan
- consideration of legislation, regulation, industry and organisational policies, procedures and
requirements
- project learnings 
- research and findings
- project outcomes
- recommendations and conclusions
- Software Development Lifecycle stages 
  o Planning 
  o Analysis
  o Design
  o Implementation/Build
  o Test
  o Deploy
  o Maintain

Getting our apprentices to structure their READMEs in a way that follows the assessment plan guidance will go a long way to preparing them for their final project report.

**Comment by sofer** [comment]
I am pretty sure that @oliverjam has this documented already, but we are thinking of introducing this structure and the reasons for it in a talk on Monday of Week 8 and adding a couple of bullet-point questions under each heading in order to make it easier for teams to complete the README (and  perhaps adding an extra question under each heading for the TfB project, to push them a bit closer to the 4,000+ words they are going to need to write next year).

**Comment by Albadylic** [comment]
A reasonable amount of this list ties in with Design week and is being delivered in some form. For FAC23 we might like to review what we're delivering to line it up a little more with the curriculum there.

**Comment by oliverjam** [comment]
Yeah the majority of what I want to cover on Monday is around how they should be thinking about technical choices/architecture before they start writing code, so hopefully not stuff they've been over this week

**Comment by sofer** [comment]
14:15-16:00 on Thursday this week. @oliverjam to prepare and present.

**Comment by sofer** [comment]
@Albadylic to do quick talk on Friday morning this week.

**Comment by oliverjam** [comment]
I delivered these slides on making technical decisions: https://fac-slides.netlify.app/slides/project-architecture/#0
and this document on README structure: https://hackmd.io/6pBEj1oGTYmJnh4k-FOu1A

We should probably repeat this at the same time at the end of each Design Week
