### ISSUE TITLE
Introducing the terminal

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#532]
It feels like introducing the terminal when we introduce Git and GitHub as part of the application prompts is too big a jump in concepts. We might like to introduce the terminal more formally as part of the prompts.

**Comment by oliverjam** [comment]
Yeah too many concepts at once. I did introduce one cohort of applicants to Git via just VS Code's GUI ages ago. There are a few difficulties with that though, cause it can't quite do everything yet

**Comment by Albadylic** [comment]
Introducing the terminal relies on folks having an idea of how their computer works - e.g. file structure.

Minimum solution is probably to add the command-line-primer or something similar to the application prompts. We should intro it one way or another.

We might like our own resource covering the fundamentals when we have time to create it. 

The connection between local / remote is more important than understanding file structure.

**Comment by Albadylic** [comment]
Relates https://github.com/foundersandcoders/tasks/issues/73

**Comment by oliverjam** [comment]
Do we want to shift the [Digital Ocean command-line primer](https://www.digitalocean.com/community/tutorials/a-linux-command-line-primer) forward from the Skills Bootcamp pre-course?

**Comment by Albadylic** [comment]
fixed by #643
