### ISSUE TITLE
Code reviewing checklist

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#534]
Following on from @oliverjam's articulation last night of a general rule that *a function either has to return a value, or be an "endpoint"*, I thought that this rule of thumb could be added to our code review checklist and then I realised that we don't have one anymore. Our [page on code reviewing](https://learn.foundersandcoders.com/course/handbook/code-review/) covers the "How?" of code reviewing, but not the "What?".

It might be worth re-incorporating some of the material from @eliascodes' [Notes on Code Reviewing](https://github.com/fac-members/master-reference/blob/master/coursebook/general/code-review.md) into the coursebook.

**Comment by sofer** [comment]
From our pre-apprenticeship feedback this week:

> I really like the idea of doing code reviews and I'd definitely like to work on that, probably next week. But if I want to make my reviews useful for someone, what should I do? What should I be focusing on? Bugs, the logic, the approach, suggest alternatives? What if I don't have a suggestion, how can I still help the other person? What if I don't understand their code? I'd like to know at some point how to do good and purposeful code reviews. 

Giving this a bump.

**Comment by sofer** [comment]
Giving this a bump again.

**Comment by oliverjam** [comment]
I cleaned up the Code Review guide in #656, turning it into more of a checklist. Next I'm going to start writing small style guides—one general one and then one for each topic that can be consulted for extra goodies each week
