### ISSUE TITLE
Friday speaker slot

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#537]
There's been some feedback that paying attention for the Friday speaker is difficult at the end of the week.

I'm not sure whether speakers should be considered as part of the core curriculum. Should they be prioritised over other activities (e.g. presentations and SGC)? Would we like to outline a core list of speakers?

In any case, this can maybe give us pause to reflect on the Friday schedule more broadly.

**Comment by Albadylic** [comment]
- Another day might work better for talks - equally, other days are already quite full and Friday seems to be the best fit.
- The end of the day is always going to be lower energy - we might like to shift the time for the slot. After lunch on a Friday or Thursday at 12:15 or 2 - for a break in the project and more the middle of the day. 
- We might like to let people head off early if the schedule finishes early

Action: Collect feedback from speakers on the timings that work for them.

**Comment by oliverjam** [comment]
Action: we'll discuss this again once we have a decent amount of feedback

**Comment by reubengt** [comment]
I think this should be discussed further before merging the new friday schedule

**Comment by oliverjam** [comment]
This is going away now right? Since we're going to be introducing the next week's topic on Fridays

**Comment by reubengt** [comment]
Keeping the speaker - just introducing the week before then.

Check https://github.com/foundersandcoders/coursebook/pull/676

For the new Friday schedule

**Comment by Albadylic** [comment]
I don't expect we'll change this, closing
