### ISSUE TITLE
Mentoring guide

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#551]
As mentioned in the FAC22 end-of-term SGC.

See https://github.com/fac-members/master-reference/blob/master/coursebook/mentorship/mentorship-techniques.md

**Comment by oliverjam** [comment]
@reubengt to add a question about mentoring to the feedback form

**Comment by Albadylic** [comment]
@Albadylic - add the 'what makes a good mentor' chat back into last couple of weeks
