### ISSUE TITLE
[testing-with-cypress] Sort out Windows

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#557]
Cypress is super annoying to get working on Windows. WSL2 can't open GUI apps by default, so the workshop instructions just don't work for people on Windows. We need to figure out a decent solution—Cypress have [their own suggestion](https://docs.cypress.io/guides/getting-started/installing-cypress#Install-pre-release-version), but it's super complicated and would probably need to be done before the workshop.

**Comment by reubengt** [comment]
Alex from fac22 has put together a guide for this, maybe worth adding to system requirements/installation guide.
https://hackmd.io/yRq2tr0BTZ6ZDSm88O13HQ?view

**Comment by oliverjam** [comment]
I think we can close this since we're dropping Cypress in #618
