### ISSUE TITLE
Wrong dates on pre-apprenticeship schedule

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#563]
Thurs 24th and Mon 28th Feb are missing.

Is it even a good idea to put dates in? Perhaps we could remove them.

See https://github.com/foundersandcoders/coursebook/blob/main/src/course/syllabus/pre-apprenticeship/testing/schedule.md

**Comment by oliverjam** [comment]
The dates are there to make it extra clear what day each workshop is on, and when homework is due. The last cohort found it a little confusing to keep track of when they should be completing each workshop by (see #540).

No idea how I got the dates so wrong though, will make a PR to adjust now
