### ISSUE TITLE
Node architecture spike - too broad?

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/coursebook#567]
Feedback from FAC23:

"I don't know if anyone else felt this but I found the spike topic of Node architecture really broad and I didn't feel that I had enough time to properly research and understand it. It was not totally clear from the spike questions to what level it is important to understand the event loop and the callback syntax, since we did not use it in the project either"

Error first callbacks aren't really covered anymore.. maybe it's worth restricting the scope of this spike? Seems like a lot of new info to cover in limited time, especially seeing as there's not really a chance to practice it.

**Comment by reubengt** [comment]
I miss the infamous wth is the event loop video 😅

**Comment by oliverjam** [comment]
Yeah we should probs rethink our approach here considering modern Node code looks v different to what you'll find in blog posts from 2014 if you google this topic

**Comment by oliverjam** [comment]
@oiverjam: to drop the callback and error conventions links since everything is promises now

**Comment by oliverjam** [comment]
We got rid of this spike so I think we can close
