### ISSUE TITLE
Switch from PostgreSQL to SQLite

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#571]
[Later edit] **We decided that switching to an ORM would be too much—we get a lot of value out of teaching SQL. However we will switch from Postgres to SQLite to avoid all the admin/setup headaches.**

It might be time to rethink database week. I think it's the least conceptually different since the curriculum rewrite, and it's very focused on absolute fundamentals. E.g.

1. Managing a local Postgres DB
2. Manually configuring env vars and setting up the connection
3. Writing raw SQL queries as strings in JS

There are important things it doesn't cover:

1. Migrations (we literally never touch on how to change a schema in production)
2. Advanced SQL queries (most projects barely have one `JOIN`)

Database week has consistently had the most frustration, problems and wasted time of any week.

1. Getting Postgres installed at all is difficult (especially on Windows)
2. The process of setting up a new user/DB + connecting in Node takes a long time to grasp
3. We spend a large amount of time context-switching to a whole new language (SQL)

Given that no final projects or TFB projects use self-hosted Postgres like this anymore (and afaik almost none of our employment partners do) we might not need to have such a low-level focus. 

## Suggested change

I suggest we switch the curriculum to use [Prisma](https://www.prisma.io/blog/prisma-the-complete-orm-inw24qjeawmb).

Prisma is a JS ORM (e.g. you write `prisma.post.findMany()` instead of `SELECT * FROM posts`), and a tool for managing local DBs. It handles all the local environment setup so we'd lose all that faff. It also has migrations built-in. It abstracts away differences between multiple different underlying DBs, so you can use Postgres/MySQL/SQLite etc without really having to change app code.

Prisma is a "platform" as well as a library—it has a newish hosted DB service, and also a data browser UI.

It's also well-funded, popular, and appears to have emerged as the "standard" solution in the Node/JS/React ecosystems nowadays. I.e. all the metaframeworks that include a data layer seem to have built on top of Prisma (e.g. [RedwoodJS](https://redwoodjs.com)).

Quote from Prisma:

> Databases are hard
> At Prisma, we found that the Node.js ecosytem – while becoming increasingly popular to build database-backed applications – does not provide modern tools for application developers to deal with these tasks.

### Downsides

Although Prisma is nice and I think would provide a smoother experience for DB week, we would be losing some things.

1. It might be useful to understand the underlying fundamentals of how a DB works (for when things go wrong)
2. We are introducing another framework/library for people to get locked into
3. An additional layer of abstraction is another level of complexity that can break

I'm not sure these are strong enough to put me off though. It's not particularly different to teaching Express instead of `http.createServer`, or spending a week on React instead of vanilla DOM manipulation. The industry is a rising tide of abstraction and we probably need to keep our heads above water.

**Comment by oliverjam** [comment]
I wonder if it would be worth surveying our graduate community to ask about tech stacks. I would be surprised if more than 5% of recent grads wrote SQL directly as part of their day-to-day dev work.

**Comment by reubengt** [comment]
+1 to surveying the graduate community about tech stacks

**Comment by sofer** [comment]
And also our employers.

**Comment by oliverjam** [comment]
@oliverjam to write a survey. Maybe send out with the Annual Report?

**Comment by sofer** [comment]
I am still a bit nervous about losing SQL altogether, but maybe it would work well as a topic for continuing apprentice learning. I suspect SQL users might be more than 5% (but probably not by much). If we thought we could create an entirely new week, TypeScript  might be worth considering. It is absolutely everywhere right now.

**Comment by oliverjam** [comment]
I think I've softened my position on an ORM, so I'm not too fussed about Prisma (although managing migrations is still important). However I now am pretty sure we should switch from pg to SQLite

**Comment by reubengt** [comment]
I'm not sure if it's changed since moving to the pre-apprenticeship model and spending an entire week on promises - but I remember async stuff being tricky for my cohort and fac18. Are there other places in the curriculum where they'll get practice writing promise based code?

**Comment by oliverjam** [comment]
Yeah they do tons of promises in the pre-app; the HTTP topic is pretty much entirely `fetch`. It's possible that simplifying the DB stuff a lot will give us the space to include some more interesting stuff in the server weeks, which could involve more promise work (fetching from 3rd party APIs etc). Right now these projects end up very simple out of necessity, because learners spend all their time/brainpower on setting up their environments.

**Comment by oliverjam** [comment]
Looking into refactoring the DB intro workshop, and ~50% of the text is Postgres setup that can be deleted. In terms of actual working time I reckon the "writing SQL" part of the workshop is maybe 25% 😅

**Comment by oliverjam** [comment]
Also I looked into the sync vs async thing a bit more. As far as I can tell the most popular SQLite library is `node-sqlite3`, which is very old and still has a callback-based API (no promises at all) 😱. Then there is the pretty tiny `node-sqlite`, which is just a _wrapper_ around the previous lib to add promises. `better-sqlite` is by far the best maintained and simplest, but just uses sync function calls. Even if we wanted to use a promise-based client I'm not sure we could 😬

**Comment by oliverjam** [comment]
This is done, so we can close and open new issues for any feedback/changes based on the first cohort trying SQLite.
