### ISSUE TITLE
Role circles - Move to thursday morning

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/coursebook#577]
I've tagged next circle but it's a change that I think can be made now.

This cohort has given feedback that role circles on wednesday feel too early on in the project to be productive, and thursday mornings feel like a better fit in the timeline for a role circle.

Have trialled it today morning and received positive feedback.

**Comment by oliverjam** [comment]
Yeah if you wanna update the schedule I'm happy with it

**Comment by reubengt** [comment]
Will do

**Comment by oliverjam** [comment]
Looks like they're still on Wednesday's in the schedule. @reubengt are they moving to another day in the new schedule?

**Comment by reubengt** [comment]
Yep they're on thursdays in the new schedule

**Comment by oliverjam** [comment]
Cool I'll close this then
