### ISSUE TITLE
Tech for Better and Design week documentation

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#579]
Right now, there's no documentation in the coursebook on Tech for Better.

We don't have a clear guide on how to run any of the workshops for the design sprints. However, we did write some Product Management documentation a while ago which could form a foundation for this.

**Comment by Albadylic** [comment]
Thinking about updating the guidance on what to do in the wireframing session relates #592

**Comment by reubengt** [comment]
I think we should make a separate issue for wireframing guidance as its writing new content rather than documenting existing processes😅 (Atleast for me it would be easier to get done if they were separate tasks rather than grouped into a megatask)

**Comment by Albadylic** [comment]
Deprioritising this for now, we can get it together slowly but first need to break down this issue into smaller parts.

**Comment by Albadylic** [comment]
I need to write something up for W/C June 20 - I'll be away so Reuben is delivering Design Week solo

**Comment by Albadylic** [comment]
Design week stuff is pretty much done, TFB will be done by the end of the year

**Comment by Albadylic** [comment]
I keep pushing this back but until I need to hand this over, I don't see documenting as a priority...
