### ISSUE TITLE
Design week feedback

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#591]
- Tech Spikes feel out of place and might be more useful later in the week. They could be swapped with project planning and code planning.
- Usability synthesis briefing should come before doing the testing. Teams could then plan their testing around the kinds of things to look for (e.g. different user paths or tasks).
- Not sure if the weighting is right for thing about look and feel vs. what does the app actually do. Maybe a little more time for code-planning.
- Tech spikes in roles might be less useful than a tech spike as a team (e.g. on a particular feature). I'm also not sure that we're explicit about encouraging use of extra frameworks

**Comment by Albadylic** [comment]
- Revisiting balance on prototyping type. We should aim for something as basic as possible but testable. The prototype doesn't need to look good, just be an opportunity for feedback. We might like to explore prototyping tools other than Figma.

The most immediate action is to move tech spikes earlier for Week 10, gather feedback and make a decision on the model of the week for FAC24.

**Comment by oliverjam** [comment]
Can we split the outcomes in two for this week?
1. Basic prototype focused on UX for testing with users: no colour/fonts etc
2. Work out design system after user testing: colours, buttons etc

**Comment by Albadylic** [comment]
I had a conversation with one of the dev's on Wednesday just after we had mentioned this and they said pretty much the same thing ☝️ 😂
