### ISSUE TITLE
Observation of Testing workshop, Week 3

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#596]
Content: Testing, Week 3 https://learn.foundersandcoders.com/course/syllabus/pre-apprenticeship/testing/schedule/
Date: 10/3/2022 
Facilitator: @oliverjam 
Observer: @sofer 

Published schedule:
* 17:00-17:15 Check-in/feedback form
* 17:15-17:45 Live project code review
* 17:45-18:30 Peer project code review
* 18:30-20:00 Project presentations

Actual:
* 17:00-17:15 Check-in/employment update (did feedback on Monday)
* 17:15-17:45 Prepare presentations
* 17:45-18:15 Peer project code review
* 18:15-18:45 Live project code review
* 18:45-19:00 Finish presentation slides. Take a break. 
* 19:00-19:50 Project presentations (finished a bit early)

Commentary:
- As usual, Oli’s issues are on point. Peer issues not bad, either. Nice to see Lighthouse being used.
- Oli is concentrating on testing for live code review and picks one project, as usual. Recording this one. We need to keep it! This code walkthrough is masterful. 1st example test done in ~15m. 2nd example in 10 mins. 3rd example in 5 minutes. Such good pacing. Nice to hear questions from the floor. 

Reflections:
- Biggest issue is that we are currently very reliant on Oli to do these live code reviews, which are clearly of great value to learners. Would be good to have other members of the team start doing these too, with Oli on hand to support and observe, initially. Also, we should keep the recordings. And we should prepare some model tests to support others doing live code reviews, even if not all live reviews are quite as structured as this one. 
- Some nice peer code reviewing, but a short code reviewing HOWTO guide for complete beginners with a checklist of what to look for would be great. Example: a reminder to run Lighthouse would probably be on the list.  
- Oli’s suggestion: that we set reviewing the issues as homework, so that learners can go back and review the issues raised and apply them to the project. We could even fit in a quick "what we fixed after the presentation" feedback round in the following week, to give some motivation and accountability without it eating into subsequent study.
- Finally, perhaps it would be valuable to have a 2nd mentor (an apprentice volunteer, probably) join the code reviewing. Oli was thinly spread, reviewing all 6 projects in 30 minutes, leaving issues on a couple of projects and working out what to do for his live review. Reviewing others' code is such a valuable skill that it seems to me to be an entirely legitimate task to ask of current apprentices as part of their learning, especially if we are also 'reviewing the reviewers', so able to give a modicum of feedback to apprentices as part of the process.

**Comment by oliverjam** [comment]
@reubengt & possibly apprentices should do some code review—we can try this out with the next set of projects

**Comment by oliverjam** [comment]
@sofer do you want to close this since there's no more action on it? The issue will still preserve the notes until you have a better system in place for tracking this stuff (I assume this will be relevant to the new QA role you're hiring for)
