### ISSUE TITLE
Guidance on how much time to spend on a take-home challenge?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#600]
Week 9 feedback:

> I'm not sure sometimes how much time to dedicate to a take-home challenge. Maybe if future employers tell us in advance how much time they expect us to dedicate to a challenge (like Turn2us did), that'd be helpful for us to better organise our time. 

So, we can certainly add a suggestion to [the guidance](https://www.notion.so/foundersandcoders/Apprentice-interview-guidance-b87e8b466ce24f2482a5763212ed858d). 

Something like: *"Aim for a challenge that you would expect a junior developer to be able to complete in under an hour. We will advise candidates to spend no more than 4 hours on the challenge."*.

I will probably do that.

However, it's not clear this will give candidates useful feedback on *"how much time to dedicate to a take-home challenge"*, because if some candidates do not follow this advice, then it will leave anyone who does at something of a disadvantage.

**Comment by oliverjam** [comment]
@sofer will try to address the concern with the learner in question

**Comment by sofer** [comment]
Have added a line to https://foundersandcoders.notion.site/Apprentice-interview-guidance-b87e8b466ce24f2482a5763212ed858d

Ready to close.
