### ISSUE TITLE
FAC23 Week 10 feedback

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#605]
Lots of useful feedback this week on aspects of Design Week and PO interaction. Here are the highlights (I think!):

> I think it would have been good to have some time scheduled to make changes to the design following user research. 

> for sprint planning it's helpful for the PO to be there to understand the plan but 2 hours is a lot especially if going into technical discussion. [1]
> it was good to have the PO present for the first hour of sprint planning, but after that it's better to work in the team to discuss the more technical aspects and start planning the issues for the project. [2]

> It would have been great to have shown our PO the prototype ahead of the user testing to get some initial feedback.

>

**Comment by Albadylic** [comment]
Some more feedback came up in SGC - this is a note to self to add it to this comment.
