### ISSUE TITLE
Split out projects and github workflow pages of handbook

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#612]
Most teams do find good ways of working, but a page of hints on how to work well together as a team, such as switching up pairs regularly, reminding each other to take breaks and the importance of the whole team coming together for reviewing and merging PRs, might be a useful addition to the coursebook.

**Comment by reubengt** [comment]
https://learn.foundersandcoders.com/course/handbook/projects/ I made an update last term so this is briefly covered [here](https://learn.foundersandcoders.com/course/handbook/projects/)
but we could separate this into another longer document.

**Comment by sofer** [comment]
@reubengt suggests two pages and will aim to do a pr before the next circle.
