### ISSUE TITLE
Focus on Software Development Lifecycle during final projects

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#636]
Reading through the portfolio criteria and understanding them, it seems like there's quite a focus on the _stages of the software development lifecycle_ in a way we're not quite matching during the projects.

We might want to reconsider design week through this lens and move away from the design-thinking / design sprint approach we're going with now. We've talked about this in some sense before (#591)

**Comment by reubengt** [comment]
Hmm I think we do actually consider a lot of things - including user testing and maintenance in our projects - what specifically do you feel is missing?

Spending extra time on really honing in on the requirements of the project and scoping it doesn't feel like a bad use of time.

Also, if we're talking about things like beta versioning we definitely don't have time in two weeks to do this

**Comment by sofer** [comment]
@Albadylic to come up with a more concrete proposal.

**Comment by Albadylic** [comment]
On looking deeper, I think we are covering the stages but not always calling them the same thing as elsewhere. The 7 stages of the cycle and where we cover them:

| Stage | Where we cover it | Changes to make |
| --- | --- | --- | 
| Planning | Discovery workshop | Framing the workshop around scoping the project through engagement with users | 
| Analysis / Defining requirements | Definition / Code planning | Combine these two activities |
| Design / Prototyping | Definition pt 2, wireframing | ... |
| Development | Build weeks | No action needed |
| Testing | During build | Add more specific focus on this as an activity |
| Deployment | During build | Add more specific focus on this as an activity |
| Maintenance | We're not | Perhaps out of scope, or it's covered in between sprints? |

**Comment by oliverjam** [comment]
We don't explicitly _do_ maintenance of existing software, but if the curriculum is good it will help them write code that will be easier to maintain. Tbh this is probably something they'll have to learn/practice with their employer

**Comment by Albadylic** [comment]
This will be done by EOW
