### ISSUE TITLE
A short slide deck on spiking and Jigsaw

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#64]
I've created a few extra slides on [spikes, jigsaw and roles](https://hackmd.io/@sofer/SkHQjoS7U).

Can we fit both [the intro to project management](https://hackmd.io/@sofer/S1wGfV2M8#/) and [Spike!](https://hackmd.io/@sofer/SkHQjoS7U#/) into [the Week 1, Day 2 schedule](https://github.com/foundersandcoders/coursebook/blob/master/week-1/schedule.md)?

Based on when both parts (weeks 1 and 2) of the original talk were presented together, I would guess that the first slide deck would need 10 minutes to present and 5-10 minute for questions. The second talk is shorter and simpler. 30 minutes is probably realistic for both together instead of the 15 minutes currently allocated.

I am a little unsure about the [Research presentation guidance](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/research-presentation-guidance.md) and *"splitting the allotted time for research 50:50 - between carrying out your research, and preparing your presentation"*, which--after our discussion this Friday--may be asking too much for what we might want to be a shorter presentation than we have asked for in the past.

**Comment by oliverjam** [comment]
We should gain 30 minutes from the morning since the Design Burst + design challenge should be an hour total. That would bring the git workshop forward half an hour so it doesn't have to run over lunch.

I agree that we need to re-visit the research guidance in light of the new focus.

**Comment by oliverjam** [comment]
Pretty sure this can be closed. We added the slides to the Week 1 schedule, and amended the research guide to fit the new format
