### ISSUE TITLE
What are we going to do with windows...

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#646]
Capturing Oli's comment from #644 

> Yeah we probably need a full curriculum issue to discuss what we want to recommend going forward for Windows. WSL2 is kind of complex for a complete beginner to set up, and seems to have a lot of rough edges down the line. We could try and get away with telling them to use Git Bash or something and deal with the slight differences in environment.

**Comment by oliverjam** [comment]
Dropping Postgres and Cypress would help a lot—those cause most of the problems

**Comment by oliverjam** [comment]
I think we should continue recommending WSL2 for one more cohort and see if avoiding Cypress and Postgres resolves most of the problems
