### ISSUE TITLE
Introduce npm, ES Lint &c. in the final weeks of the Skills Bootcamp

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#648]
Earlier than Week 3 of the full-time programme at least!

**Comment by oliverjam** [comment]
This was in a Testing Week spike topic that is now no longer delivered (as we don't have time for Spikes on the Skills Bootcamp).

My plan is to introduce this as part of a "dev environment" topic in the final few weeks of the SB—npm, local modules like Prettier/ESlint, etc
