### ISSUE TITLE
SGC

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#649]
I really miss SGC in person. Is there anything that we can do to address that?

Online, SGC seems to me like less of a conversation between learners and ends up with us not just facilitating, but also responding to each issue.

Is there anything we can, or even should, do about it?

**Comment by reubengt** [comment]
I really hate the remote friction of "oh i have to unmute to speak" that prevents people from saying things at SGC -_-

Would be in favour of moving fridays back in person

**Comment by oliverjam** [comment]
Fridays are moving back to in-person for the next cohort right? So we should be ok to close this

**Comment by reubengt** [comment]
Yeah happy to close
