### ISSUE TITLE
Video resources

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#650]
FAC24 brought up having more video resources. Someone suggested that each workshop could have a paired video version. I pushed back to say we couldn't really do that but they could, or to look for content on Youtube. They asked if we could recommend some good channels.

**Comment by oliverjam** [comment]
Relates #529 #345 #250 #227 😅

**Comment by Albadylic** [comment]
Hahah 😂

**Comment by Albadylic** [comment]
I guess the main reason we've not done this yet is that it's hard to maintain and find relevant and good content. I think the thing I'd like to discuss is if we want to / have capacity to put some effort into finding a set of video resources each week - or do nothing.

**Comment by oliverjam** [comment]
I am constantly torn on this—I would love to just sit and record myself speedrunning each project (I actually had a serious plan to do this around FAC19/20), and I think based on the live code review feedback this would be well received. However I don't know how I feel about giving them that type of resource _before_ they do the projects. Maybe it's fine that they'll end up following along? I guess it could provide the bones of the setup, and let them take it from there to add all the fun creative features.

**Comment by sofer** [comment]
At some point, and soon, we will probably have resources to make our own videos, if we want to.
