### ISSUE TITLE
Rework design week learning outcomes

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/coursebook#654]
Can we split the outcomes in two for this week?

Basic prototype focused on UX for testing with users: no colour/fonts etc
Work out design system after user testing: colours, buttons etc

based on discussion from #591 we agreed to change this for FAC24. Happy to take the lead on this.

**Comment by Albadylic** [comment]
I think we might be a bit late on this for FAC24's design week because they've scheduled the UT already. It wouldn't be a bad idea to get this in for TFB though.

**Comment by reubengt** [comment]
@Albadylic to make a pr for tfb design

**Comment by Albadylic** [comment]
Updated in #692
