### ISSUE TITLE
Trial the new approach to workshops in Weeks 6-7

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#655]
See #653. 

Set the workshops as homework on Thursday of Week 6 and then go through them together on the Monday of Week 7.

**Comment by oliverjam** [comment]
Can we pick one of this, #653 or #630 and close the other two? 😅

**Comment by sofer** [comment]
#653 and #655 relate to different programmes and have different actionable outcomes, but #630 could perhaps be closed.

**Comment by oliverjam** [comment]
Ah I missed the pre-apprenticeship schedule sorry

**Comment by oliverjam** [comment]
Discussed and decided the hybrid model we have now makes sense for the pre-app. We are still considering this for full-time though

**Comment by sofer** [comment]
Really helpful discussion. Thank you @oli.
