### ISSUE TITLE
Advice on pairing in handbook

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#659]
I couldn't see a link to any advice on pairing in the handbook. Where is it?

**Comment by oliverjam** [comment]
Huh, it's still here https://learn.foundersandcoders.com/course/handbook/pair-programming/

but I can't find a link to it from anywhere else. It must have been lost from the schedule at some point

**Comment by reubengt** [comment]
@reubengt to add this to "mentoring expectations" exercise. Get the cohort to create a list of what works when pairing.

then restructure this https://learn.foundersandcoders.com/course/handbook/pair-programming/ into bullet points

**Comment by Albadylic** [comment]
Adding this to my backlog
