### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#66]
I think we need to decide on a license for our curriculum. We need to re-apply for our Netlify open source account, which requires our "project" to be licensed with a valid open source license. Since the curriculum is our main product this is probably what they care about.

Also I was thinking about other commercial bootcamps using our curriculum (e.g. http://www.turnintocoders.it/en/). I strongly believe that our curriculum should be open source, but I really don't like the idea of my work being used by for-profit entities.

My suggestion would be to use the Creative Commons Attribution-NonCommercial-ShareAlike ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)) license. This allows others to share and adapt the content, but requires them to give us attribution, not use the content commercially, and to retain the same license.

**Comment by sofer** [comment]
@oliverjam my only thought is: are we ourselves subject to the terms of this licence or are we uniquely able to deliver some of this content in a commercial setting (say doing in-house training for a commercial partner) where our own use is primarily intended for commercial advantage or monetary compensation?

**Comment by oliverjam** [comment]
We still retain the copyright, we're just licensing some of our rights to others. So as far as I can tell there would be nothing stopping us using the content commercially.

> I personally see nothing wrong with you wanting to reserve your commercial rights
- https://creativecommons.org/2005/12/07/ccinreviewlawrencelessigonimportantfreedoms/

**Comment by sofer** [comment]
You're right. I am in favour of CC BY-NC-SA 4.0.

**Comment by macintoshhelper** [comment]
Any thoughts on Linux-style GPL, or CC BY-SA? I find Linux's model of allowing commercial use interesting, with the restriction of any derivative work needing to be open-sourced, contributing back to the original project (resulting in Android, etc).

Not sure how that would work in practice though, software is probably a bit of a different world compared to course material.

**Comment by oliverjam** [comment]
@macintoshhelper I would really rather not allow commercial use at all for now. One of FAC's primary values is free access to the program. It would undermine that to have other bootcamps charging for the curriculum that we spent a huge amount of time and effort on.
