### ISSUE TITLE
Portfolio Evidence gathering activity on Friday

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/coursebook#669]
(the new friday schedule means presentation prep is duplicated)

**Comment by Albadylic** [comment]
I can pick this up while I write some DW docs for ya

**Comment by reubengt** [comment]
gonna leave this open as there's still a fix for the final few weeks - my bad, the issue was confusingly named

**Comment by Albadylic** [comment]
I'm not sure what you wanna do with the extra time. They've wound down on building by Friday, I'm not sure if they need more time for planning. Did you have something in mind?

If we want to add something new, I'd suggest 'Portfolio evidence gathering' which relates to EPA and https://github.com/foundersandcoders/tasks/issues/147

**Comment by Albadylic** [comment]
@Albadylic to prep something for Build 1

**Comment by Albadylic** [comment]
10:00 - [Portfolio slides](https://fac-slides.netlify.app/slides/portfolio/#0)
10:15 - [FAC standard](https://fac-standard.netlify.app/)
10:30 - Gather evidence
11:00 - End

For the further weeks, @reubengt , they should know what to do and can spend the full hour gathering evidence. Reassigning to you to review / ask any questions and close this if you're happy with it.

**Comment by reubengt** [comment]
@Albadylic thanks! looks good! One q - are we offering feedback on their evidence gathering of any kind? I suppose until one round of apprentices goes through the gateway there's no real way for us to tell what's right or wrong.

**Comment by Albadylic** [comment]
@Albadylic to give teams feedback, if they send me their drafts

**Comment by reubengt** [comment]
closing this
