### ISSUE TITLE
Reset in-house design week changes made during FAC24

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/coursebook#671]
(for next term)

**Comment by Albadylic** [comment]
Wait, what were the changes?

**Comment by reubengt** [comment]
I believe only web science moving to friday.
https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens lets you see revisions line by line in vscode btw 😄

**Comment by reubengt** [comment]
The whole schedule is changing and this will be caught there.
