### ISSUE TITLE
Pre-apprenticeship Weeks 6-8 timetable changes

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#672]
@oliverjam's unexpected absence this evening caused a tweak to the schedule. Instead of Oli going over the solutions, I put people into groups of 4 to go over the solutions together. Unsurprisingly it went well, but equally unsurprisingly most of them also missed Oli going through the solutions. A quick straw poll brought the apparently unanimous view that learners would prefer to do workshops at home and go through solutions together before getting a run through from Oli. The upshot is that it probably makes sense to adapt the schedule for Weeks 6-8 more or less as follows:

Week 6 Thursday homework:
- [Build a testing library](https://learn.foundersandcoders.com/workshops/learn-testing/)
- [Unit testing workshop](https://learn.foundersandcoders.com/workshops/learn-unit-testing/)

Week 7 Monday:
- 17:00-17:15 Check-in
- 17:15-17:45 [Intro talk](https://fac-slides.netlify.app/slides/testing/)
- 17:45-18:45 Peer-led tutorial groups of four
- 18:45-19:45 Workshop discussion & solutions
- 19:45-20:00 Check-out

Homework:
- [Integration testing workshop](https://learn.foundersandcoders.com/workshops/learn-integration-testing/) (2 hours)
- [TDD workshop](https://learn.foundersandcoders.com/workshops/tdd-array-methods/)

Week 7 Thursday
- 17:00-17:10 Check-in
- 17:10-18:00 Employer Q&A
- 18:00-19:00 Peer-led tutorial groups of four
- 19:00-19:45 Workshop discussion & solutions
- 19:45-20:00 Check-out
 
Week 8 Monday
- 17:00-17:15 Check-in
- 17:15-17:30 Weekly survey
- 17:30-18:30 Employment preparation
- 18:30-19:45 [Project](https://learn.foundersandcoders.com/course/syllabus/pre-apprenticeship/testing/project/) introduction
- 19:45-20:00 Check-out

I am a little unsure about the exact scheduling, in particular what the optimum time is for both peer-led groups and whole-class discussions. 

Related to #630.

**Comment by oliverjam** [comment]
I do prefer this as a model, and we should definitely try it for this term. However it does make the programme more reliant on having a technical mentor who is proficient at explaining the concepts on the spot, which is not necessarily something FAC will always have around. I.e. how do we wrangle this when I'm not here?

**Comment by oliverjam** [comment]
It doesn't really make sense to have the intro talk _after_ the initial workshops—since these are all recorded now we can provide this as the first bit of homework before the first session of the topic. There's not a huge amount of benefit to these being delivered live/synchronous

**Comment by reubengt** [comment]
@sofer or @oliverjam to discuss and make a PR for new schedule
