### ISSUE TITLE
Documentation for mentors

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#677]
In preparing for next week, I've added some documentation on Design Week (#674). I added a new section for `mentoring` which I imagine we'd add to over time and at some point integrate with the platform so it's only visible to those who have completed their training.

**Comment by reubengt** [comment]
make a section for this in the coursebook

**Comment by Albadylic** [comment]
On reflection, I'm less convinced this fits as part of the navigation on the coursebook. I'd push for it to be it's own section like 'course' or 'resources.

We'll have a significant amount of documentation and different levels of nesting. For example, Design Week would need notes on each workshop, plus the week as a whole, plus how it fits with Software Development cycle. Each of the six weeks of the programme will likely have one document, if not many.

**Comment by ivanmauricio** [comment]
@Psydwinder to use chatgpt to make information on this [page](https://learn.foundersandcoders.com/course/handbook/mentor-guidance/) more digestible

**Comment by sofer** [comment]
If the guidance cannot fit on a single screen, it may be too long.

Mentors have all recently been through the programme. They should understand how it works. The current documentation can probably be distilled to a handful of things to be aware of.
