### ISSUE TITLE
Set up regular 15 minute slot for final project process

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#689]
- should we select teams earlier;
- should they be working on product ideas earlier;
- should they be scheduling user research and testing in advance?

**Comment by Albadylic** [comment]
Set up a regular 15 minute slot each week. This will be used for the Software Development Process talks and preparing for final projects.

| Week | Activity |
| --- | --- | 
| 1 | [Intro to Project Management](https://fac-slides.netlify.app/slides/proj-mgmt/) |
| 2 | [Issue Management and Estimation](https://fac-slides.netlify.app/slides/estimation/#0) |
| 3 | [Intro to final projects](https://hackmd.io/@jamdelion/Skhetr0dF#/) |
| 4| Draft a project idea - i.e. open an issue on final-project-ideas repo |
| 5 | Choose a project idea |
| 6 | Schedule research and testing |
