### ISSUE TITLE
Reformulation of tech spike and project structure

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#691]
See https://github.com/foundersandcoders/coursebook/issues/630#issuecomment-1170032078:
> ## Projects
> 
> - Tech spikes are not relevant enough to the projects right now
> - Projects should have at least one (or a few options of) technical problems to solve beyond the week's "boilerplate"
> - We might want to consider much more specific project ideas so people don't get lost at the creative step
> - A better project structure might look like:
>    1. Solve the technical problem (a spike with throwaway code)
>    2. Come up with an idea/plan the project
>    3. Build the actual features (should be simpler since the hard part is already solved)
>    4. Respond to feedback (after code review)
>    This is more similar to the structure of a real project, where you wouldn't just dive into building something from the start

**Comment by oliverjam** [comment]
Documenting which spikes we definitely need to keep in some fashion:

## Server

- Heroku deployment
- ~Client vs server~ [not interesting or important]
- ~Node architecture~ [actively harmful as the callback stuff isn't relevant now #567]
- ~Modules~ [mostly covered in our npm intro]

## Database

- ~Relational vs non-relational~ [covered in intro talk]
- ~Database security~ [not super relevant in a world of hosted DBs]
- ~Schemas and relationships~ [covered in other material]
- Continuous Integration

## Authentication

- ~HTTPS~ [interesting but not that relevant]
- ~Stateless vs stateful authentication~ [covered in other material]
- ~Browser storage~ [not relevant this week, possibly confusing]
- Attacks

## Server Side App

These are all project-focused features so we can probably keep them. Not sure anyone has ever done email so we could drop that one.

## Client Side App

Has never had spikes.

## Full Stack App

Has never had spikes.

**Comment by sofer** [comment]
Relevant feedback from FAC24 this week (Week 10):
> I didn't think the spike presentations in this week were very productive. It was a little repetitive and took time that could have gone towards the project.

**Comment by Albadylic** [comment]
This is fixed by #676

**Comment by oliverjam** [comment]
@Albadylic I think this issue is less about the new schedule and more about what exactly the spikes and projects should be. I.e. we discussed potentially providing more specific guidance on what features to build etc.
