### ISSUE TITLE
Foundation course improvements

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#699]
- [x] #486 
- [x] #648 
- [x] #698 
- [x] #688 
- [x] #706 
- [x] #738 
- [x] #751 
- [ ] #788
- [ ] #750 
- [x] #812

**Comment by sofer** [comment]
Doing the schedule on a just-in-time basis and it's going well.

It's just possible that for the first time in six terms there may be no significant changes to the schedule next term. 

The slides are going up on a newly-created FAC team on hackmd.

**Comment by sofer** [comment]
See #738

**Comment by sofer** [comment]
Just about ready to re-jig the schedule now.

See e.g. https://learn.foundersandcoders.com/course/syllabus/pre-apprenticeship/http/schedule/

**Comment by Albadylic** [comment]
One 3 week cycle is done, schedule will be ready by end of sprint

**Comment by sofer** [comment]
Ongoing. I am not gong to commit this to the coursebook until the end of term. Removed next circle label.

**Comment by sofer** [comment]
Still doing this on a just-in-time basis.

**Comment by ivanmauricio** [comment]
see here for latest iteration of schedule + ideas on evolution of Foundation programme: https://www.notion.so/foundersandcoders/Standing-Agenda-e2bbd54200aa42f6b9416f868e4e7bc6

**Comment by ivanmauricio** [comment]
@ivanmauricio to arrange session with dan to see what's the next steps on this one

**Comment by eliazzo** [comment]
Can we add these to the coursebook somewhere more accessible? 🙏🏽

https://learn.foundersandcoders.com/workshops/node-npm-intro/

https://learn.foundersandcoders.com/workshops/dev-tooling/

**Comment by ivanmauricio** [comment]
from closed #812

> Week 1: Markup

[learn.foundersandcoders.com/course/syllabus/pre-apprenticeship/markup/project](https://learn.foundersandcoders.com/course/syllabus/pre-apprenticeship/markup/project/)

Stretch Goal
Use the automatic trigger functionality of your [GitHub project board](https://help.github.com/en/github/managing-your-work-on-github/about-project-boards).

We don't introduce projects, also the link goes to the old GitHub project board.

The copy, "for the next couple of days", needs to be removed

**Comment by ivanmauricio** [comment]
I'm going to close this issue as it was a catch-all for foundation programme improvements which have mostly been done

the only things left are issues #750 and #788 but as they are separate issues with people assigned to them, they are more easily tracked individually

https://github.com/foundersandcoders/coursebook/commit/9b92b98273a439b6053e362f3e009fe58c7bbf33
https://github.com/foundersandcoders/coursebook/commit/9b92b98273a439b6053e362f3e009fe58c7bbf33
