### ISSUE TITLE
More reminders to check learning outcomes

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#707]
> FAC could also provide frequent reminders to check the LO's at the start of every week.

**Comment by reubengt** [comment]
👍 This is actionable for next term - each mentor from fac24 can remind fac25 to do this 😄

**Comment by Albadylic** [comment]
Adding next-circle as I'm not sure this is being actioned

**Comment by Albadylic** [comment]
Dan has implement this on the SB, with an end of topic survey asking for each LO how each learner feels about it out of 5.

Can we implement this on the FT programme? We'll review at the end of term and Dan will feedback on how it went on the PT programme
