### ISSUE TITLE
More notice to schedule user testing

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#708]
> Not sure how much notice PO's had to organise user testing but our PO suggested it was only about a fortnight. Assuming that's true, it might be worth telling them to start organising users from their week 1? (If possible.) At least to give them the dates and times that user testing should take place, so they can choose to get something organised if they want.

**Comment by reubengt** [comment]
This is tricky because user testing only happens if the project is selected @Albadylic may have more thoughts

**Comment by Albadylic** [comment]
A PO has suggested in the past that we could ask everyone to schedule users and cancel them if they're not selected. I always share [this documentation](https://foundersandcoders.notion.site/Tech-for-Better-d49b1f9b269443f3a039cb6bf615638d) at the start of the programme, which includes a schedule, but I don't know that it is read in detail 😅

**Comment by Albadylic** [comment]
Relates #579

**Comment by Albadylic** [comment]
I gave them more notice this time. Closing.
