### ISSUE TITLE
More guidance on what makes a good usability interview

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#709]
> Maybe a quick presentation on what makes a good usability interview/interviewer in general? Not completely necessary as we could google this but some advice at some point would be great

**Comment by reubengt** [comment]
https://docs.google.com/presentation/d/10VxYiFBmwLevEH3V6AP74ibf_JRt51Gd-295TICrWQU/edit#slide=id.g87e8f70714_0_133

This was definitely delivered this term. Again maybe a case of online delivery and people being less attentive. We could review this presentation but I think it covers a lot?

**Comment by reubengt** [comment]
On reflection - I delivered this in person during the Ofsted inspection week

**Comment by reubengt** [comment]
The action here is to repeat the talk in tech for better design week.

**Comment by Albadylic** [comment]
Relates #579
