### ISSUE TITLE
Friday afternoon schedule

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#72]
The Friday afternoon schedule currently includes:

| Time  | Activity            |
| ----- | ------------------- |
| 14:00 | Presentations       |
| 16:00 | Stop Go Continues   |

Given recent discussion on keeping presentations to under 10 minutes and FAC18's requests for feedback on their presentations,  we may have additional time for other activities. It might be a nice addition to have space for 20 minutes of peer (i.e. team-to-team) feedback on presentations, supported by a README with guidance on things like, scripting (or even pre-recording) the app walkthrough and keeping code snippets and explanations short. We could usefully also add additional time for team-based SGC, which appears to have been missed out of the current weekly schedules.

| Time  | Activity            |
| ----- | ------------------- |
| 14:00 | Presentations       |
| 15:20 | Presentation feedback    |
| 15:40 | Team SGC       |
| 16:00 | Stop Go Continues   |

**Comment by oliverjam** [comment]
I think "Stop Go Continues" was meant to encompass both team and cohort SGC. I agree that feedback is a good thing to schedule

**Comment by sofer** [comment]
> I think "Stop Go Continues" was meant to encompass both team and cohort SGC.

In which case, I am not sure that 45 minutes is long enough, although I am not entirely clear of the relationship between *"updating user manuals"* and Team SGCs. It might be worth having a little bit more clarity around the Friday afternoon schedule.

**Comment by oliverjam** [comment]
I think this is done?
