### ISSUE TITLE
React/Next testing

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/coursebook#732]
Now that we've dropped Cypress from the main curriculum we don't have a good testing story for React/Next apps. These are a lot harder to test with the simple Node-based testing we do in the first few weeks, since they involve so much non-standard JS (JSX) or compiler magic (Next routing etc).

Next does have [a page on testing](https://nextjs.org/docs/testing) with various technologies, so in the spirit of that week being about learning to use external resources/teach themselves, we could just link them to it and say "figure out how to test your app".

Alternatively I could try to figure out a really simple/minimal way to test React components without all the heavyweight stuff.

**Comment by oliverjam** [comment]
We also need to figure out where this should go. React Week is already too full so it'll probs have to be Next week. We have the whole Monday for learning now, which is I think longer than last time to do the Learn Next.js tutorial, so we might be able to slot this in too.

**Comment by oliverjam** [comment]
I think the simplest solution is just to recommend they do the Next testing guide (maybe pick just one of the libraries) after they do the main Learn Next workshop. We'll need to add that to the schedule.

**Comment by Albadylic** [comment]
I'd probably suggest [Playwright](https://nextjs.org/docs/testing#playwright) which I believe has been used a bit in the past

**Comment by oliverjam** [comment]
Yeah Playwright is nice and probs the closest to how they've been testing up until that point. Not too different to Cypress (just more modern) so the mentors should be ok with it too.

**Comment by Albadylic** [comment]
@ivanmauricio is gonna have a play with Playwright
