### ISSUE TITLE
Understanding a big codebase

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#737]
A few apprentices have fed back that when they started with their employers they felt a little overwhelmed figuring out how the codebase fits together and where to be doing the work that is required.

Oli (FAC23) suggested an exercise on this towards the end of the course. Given that it's been a common concern, I wonder if we could add something to the curriculum.

**Comment by sofer** [comment]
Perhaps a day of picking up a ticket in pairs on an open source project and seeing how far they get with it?

**Comment by Albadylic** [comment]
Sometime in the TFB would be a good fit for time
We'd need to find a good OS repo, so there's a decent bit of research to do here

**Comment by oliverjam** [comment]
The `fac-account` project probably counts as big enough if you wanted something internal? It's a private repo though, not sure how you'd feel about giving learners access.

**Comment by Albadylic** [comment]
Good call. In theory, I'd be happy to share the code. We could easily fork or copy across a public version so production isn't effected.

**Comment by sofer** [comment]
Open source it.

**Comment by oliverjam** [comment]
I think these were the reasons we made it private:

1. Some amount of security through obscurity. All the logic happens on the server so this makes it pretty tough for anyone to bypass various checks even if we've made an implementation mistake.
1. Hiding our decision-making processes. The app logic effectively encodes FAC's entry requirements and other stuff we might not necessarily want public.

But it was mostly out of an abundance of caution I think—there's no reason it couldn't be opened up.

**Comment by Albadylic** [comment]
- We're keen to use the accounts platform, and if possible make some real updates to it that are useful to us; and if we're happy with sharing it with the cohort.
- @ivanmauricio to arrange time to chat to @oliverjam about where the platform is, and what work we might like to do on it. And about protecting branches.
- @Albadylic to chat to Oli J, if we feel we'd like him to be involved
- @ByteSizedIT to figure out when we might have time for this in the last week

**Comment by Albadylic** [comment]
Friday of In-House Build 2 is maybe the time to do this. We're keen to use our platform.
