### ISSUE TITLE
Employment Morning

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#744]
Review the purpose/need Employment Morning - currently in schedule for Tuesday at 09:45-13:00 during build week 1 for the In-House project

**Comment by sofer** [comment]
Added a "Fridays are a good day" note to the apprenticeship handbook.

https://foundersandcoders.notion.site/8-Onboarding-and-ongoing-support-8be02823d33c4fd99c82578a8fbc9612
