### ISSUE TITLE
FAC25 - SGC Feedback

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#745]
Action taken by Gregor & Neville, from FAC25 SGC (Week 2), to discuss the following suggestions in the Curriculum Circle:

- Enable more time to review the sessions and the associated concepts/code

- Switch Presentations around with Code Review, the suggestion being that the groups will be more familiar with each others projects and it will be easier to engage in their code

**Comment by Albadylic** [comment]
We're not convinced that swapping presentations and Code Review makes sense.

We could give a demo of how to code review in the first week (e.g. pull it, run it, click around...). Ivan will introduce this in his code review tomorrow morning.
