### ISSUE TITLE
Week 1 Schedule

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#75]
Couple of minor things but wanted to raise them here. Happy to self-assign these if all agree.

- [x] Course schedule links to the old coursebook, needs updated to link to default schedule in GitBook
- [x] Can we replace intro to consensus-based decision making with a practice sociocracy circle? Think this is what Bobby did and since we're perhaps changing our business meeting model this might be more apt
- [ ] Revisit the presentation guidance for days 2 and 5. Relates #14 #64 #72

**Comment by oliverjam** [comment]
These are all the documents used in Week 1:

- [ ] [Code of Conduct](https://github.com/foundersandcoders/our-site-v3/blob/master/src/pages/documents/code-of-conduct.md)
- [ ] [House Rules](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/house-rules.md)
- [ ] [Pair Programming](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/pair-programming.md)
- [ ] [Consensus decision making](https://github.com/foundersandcoders/hq/blob/master/cooperative-structures.md) (maybe we're scrapping this in favour of something on sociocracy?)
- [ ] [Spike presentations](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/research-presentation-guidance.md)
- [ ] [Code review](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/codereviewintro.md)
- [ ] [Projects](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/weekly-projects.md)
- [ ] [Retrospectives](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/retrospectives.md)

@Albadylic would you mind adding all these to the new coursebook? Maybe in a `handbook` subdirectory? Or `documents` or something? I think we might also have to configure the navigation in the `SUMMARY.md`

**Comment by sofer** [comment]
> Consensus decision making (maybe we're scrapping this in favour of something on sociocracy?)

Yes, scrapping.
