### ISSUE TITLE
Add post-course to foundation

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#751]
- Working on Execute Program
 - Completing a project (or two)
 - Anything else?

**Comment by sofer** [comment]
- Social Machine reading list.

**Comment by sofer** [comment]
Relates to #699

**Comment by sofer** [comment]
Not for this sprint. Needs to be ready by the end of term, though.

**Comment by sofer** [comment]
Not sure if it was. Added next circle label back and unassigned myself.

**Comment by ivanmauricio** [comment]
done here: https://github.com/foundersandcoders/coursebook/commit/21a5f46564f47fc87415a1b5c4bf52adbc6896aa

closed
