### ISSUE TITLE
Workshop timings & delivery

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#755]
In SGC (week 3), there was mixed feedback from the cohort on how much they could do within the 8 hours on Monday. I'd say it was roughly:

- 1/3 of the cohort feel they can complete the work comfortably in the time (or less time)
- 2/3 feel they need at least 1/2 a day more time
- 1/3 are sometimes completing things in time, and sometimes taking more time

I'm not sure there's a clear action from this, and the feedback is pretty mixed. Our move to Fridays for workshops next term will help resolve this. But for those not completing things on the workshop day, and without time available at the weekend, are at risk of falling behind. We might like to think of some mitigation strategies.

**Comment by ByteSizedIT** [comment]
Related to this was the suggestion that preview/review of workshop content, similar to the pre-Apprenticeship course, would be valued by some. Overlapping suggestion was also made re refactoring the Intro talks a little to make them more specific to the workshops themselves.

**Comment by Albadylic** [comment]
@ByteSizedIT to collect feedback on hours per workshop from FAC25

Review at EOT

**Comment by ByteSizedIT** [comment]
Retrospective feedback for FAC25 was not the very clear. Asking for time spent each week in the FAC26 feedback form.

Details of the responses to this question are summarised in the Airtable Gallery [here](https://airtable.com/appKA4hcyDYWp46Mx/tblf1AmenpkfijNPt/viwMk1UhUFKh2rkqU?blocks=hide)

Week 1, the mean average of 8 responses was 10hrs 36mins (with individual answers ranging from 5 to 20 hours)

**Comment by ByteSizedIT** [comment]
Week 2, the mean average of 9 responses was 10hrs 20mins (with individual answers ranging from 5 to 15 hours)
Week 3, the mean average of 8 responses (so far) was 10hrs 30mins (with individual answers ranging from 6 to 15 hours)

Wider question re measuring learning; On pastoral walks 1 learner has suggested they spent 14 hour reviewing previous weeks workshops (going back to Node and Github) instead of the week 3 Auth workshop.

**Comment by Albadylic** [comment]
I had an interesting conversation with someone from FAC26 about the format of the workshops. They had found they're spending a long time on the workshop and still going into the project feeling behind everyone else. Reading isn't an effective learning mechanism for them in particular and many others...

**Comment by ivanmauricio** [comment]
students have been enjoying having more time with an experienced person, do we want to increase this type of contact time to the schedule?

https://github.com/foundersandcoders/coursebook/issues/784

**Comment by Albadylic** [comment]
Proposal: Fridays become a lightly facilitated room where the cohort come into Space4 and work in their own way through the workshop.
