### ISSUE TITLE
Code Review, Sprint Planning, Intro to Next Week (Final Projects)

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#757]
Review and action suggested changes to weeks 7-12, as previously discussed on Discord:

- Bring ' Code Review' + 'Sprint Review and Planning' forward to Thursday afternoons.
- Make 10-12 on the Fridays 'Respond to Issues/Build' (brought forward from Mon)
-  Remove 'Intro to next week' in final project weeks (besides introducing Build during design, which just now has it's own slot but should be moved down into the regular slot).
- Add [Project Documentation](https://learn.foundersandcoders.com/course/handbook/project-documentation/) in place of the removed 'Intro to Next Week' sessions

**Comment by Albadylic** [comment]
go, go, go

**Comment by ByteSizedIT** [comment]
Scheduled updated as above and merged with the exception of:
"besides introducing Build during design, which just now has it's own slot but should be moved down into the regular slot"

Introducing next week slot has been replaced with Project Documentation for Design Weeks also - need to double check this with Gregor
