### ISSUE TITLE
In-House Design Week Review

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#769]
@Albadylic and @ByteSizedIT to review the schedule / content in light of FAC25, incl:

[ ]  Align with 4 day week?
[ ]  Reduce User Research and Feedback meetings to 6, making them 90min sessions - allowing 15mins more break and 15 mins more synthesis?
[ ]  Put slides re synthesis before second user session - so that apprentices see how to collect data ahead of meetings

**Comment by Albadylic** [comment]
I'm happy with all these actions. I'm not sure we need to discuss, but just to action these?
