### ISSUE TITLE
Tech interviews: a possible peer-led approach

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#77]
Becoming good at technical interviews is a critical skill. It could also become somewhat labour-intensive if we were to offer more opportunities for students to practice if done in the traditional way. It also requires the interviewer to have a modicum experience to be effective. Let's explore peer led approaches.

Perhaps we could set aside 90 minutes at the same time each week from Week 11 to trial peer-led approaches to interviewing.

Here is what it could look like:

### Team of 4 + mentor
- Interviewee
- Interviewer, pairing at laptop
- Assistant, providing support to interviewer, upon request, but not communicating directly with interviewee
- Observer, saying nothing, but taking note of interactions and feeding back on them at the end of the interview
- Mentor, sits in on interviews and can either take the role of meta-observer or can just get on with their own work. Their main role is to say nothing, frown from time to time and generally unnerve the team. They can join the feedback session at the end of the interview, if they want, but they don't have to.

### Library of interview challenges
Library of challenges with associated documentation

### Documentation
- description of the problem
- Pre-populated codepen or similar environment, if needed
- List of FAQs and allowable responses
- Outline model solutions

### Process

1. Mentors pre-prepare 4 problems and associated FAQs
1. All members of the team should prepare for their role as interviewer by memorising one problem, the associated FAQs and by attempting to solve the problem themselves before looking at the model solution 
1. Interviewee sits at laptop and casts their screen
1. Interviewer sits with candidate; assistant and observer sit at side 
1. Interviewer describes the challenge; If the assistant is not happy with the description, then they will offer clarification
1. Interviewee asks questions; interviewer responds to questions without referring to FAQs; if they are unsure of the appropriate response they will ask the assistant, who may respond using the FAQs as a reference; 
2. The observer will take note of any interactions that they want to feedback on and any questions that they or the assistant think need to be added to the FAQs 
5. The interview ends after 15 minutes
6. The observer then leads a feedback session for all participants and makes a PR for any suggested updates to the FAQs
7. Everyone changes roles and the interview proceeds with a new challenge

**Comment by sofer** [comment]
Some reflections on sitting in on the whiteboard and pairing sessions:
- It's not necessarily a good use of time for the students who are not being interviewed
- We can have a quite supportive (interventionist, even) approach to being the interviewer
- The expert knowledge of the interviewer is helpful in steering the interview, but it's not clear how necessary it is to the process and how we might be able to make an interview meaningful without that knowledge
- Putting people on the spot and making them nervous looks like it is an important part of the process

**Comment by bobbysebolao** [comment]
To add to the above feedback:

- If possible, it's definitely preferable to have panels of 2 interviewers, when conducting the interviews solo it is more tricky to provide interviewees with meaningful feedback
- Choosing technical interview questions that have 'stretch solutions' seems like a good way to give every interviewee an appropriate challenge, regardless of their ability level
- Progressively ramping up the difficulty of technical questions until the interviewee does not know the solution seems like a good way to apply pressure
- Sharing the interview questions with the interviewees afterwards was appreciated

**Comment by sofer** [comment]
@sofer to review. See also https://hackmd.io/@sofer/HkI__tUf_.
