### ISSUE TITLE
Review Heroku use/alternatives in the f/t curriculum

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#773]
Replacement needs to be identified and included within the curriculum in time for the FAC26 f/t course.

Heroku is used to deploy projects for weeks 1-4 and 6. 

There are 2 issues with this:
- The Heroku free tier is no more
- Data in the SQLite database taught within the curriculum does not persist on Heroku

Ref:
Discussion in Curriculum channel on Discord beginning here: https://discord.com/channels/832220048172908545/933002275197190184/1024005873070260224

**Comment by Albadylic** [comment]
https://render.com/

**Comment by Albadylic** [comment]
Ivan will do a deep dive and figure out how to get something deployed somewhere

**Comment by Albadylic** [comment]
Ivan's gonna document fly.io in the curriculum by start of next term

**Comment by ivanmauricio** [comment]
Look for pricing plan that would allow:

- 3 teams to keep projects on there for x amount of time

@ivanmauricio to look into pricing options and suggest a good tier

**Comment by Albadylic** [comment]
Ivan bought some credit
