### ISSUE TITLE
Tech for Better one pager

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#774]
We have [documentation for Product Owners](https://foundersandcoders.notion.site/Tech-for-Better-d49b1f9b269443f3a039cb6bf615638d).

We don't have documentation for our developers. Let's add a one page summary into the handbook on what happens in Tech for Better each week.

We could have sub-headings for each week, which are linked from the weekly schedule.

**Comment by ByteSizedIT** [comment]
Linked to #780 - Review sequencing of TfB workshops
