### ISSUE TITLE
Review sequencing of TfB workshops

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#780]
@Albadylic  to arrange a time

User Stories might be better to come before Wireframing

**Comment by Albadylic** [comment]
We aim for 8 Product Owners, and can split them into two groups of 4 (A and B).

### Current sequence

| Week | Title | Activities |
| --- | --- | --- |
| 1 | Introduction | Introduce Devs and PO's to TFB |
| 2 | Product Pitches | Meet all PO's |
| 3 | Discovery | Discovery workshop with Group A |
| 4 | Discovery | Discovery workshop with Group B |
| 5 | User Research | PO's conduct user research |
| 6 | Research synthesis | All PO's synthesise results from their research |
| 7 | Product Management | User stories and sprint planning with mock Product Ideas |
| 8 | Selection | Cohort select products to work on |
| 9 | Analysis | Mapping, HMW, Consequence scanning with chosen PO |
| 10 | Design | Definition, Prototyping, Testing |
| 11 | Build | First build sprint | 
| 12 | Build | Second build sprint and Showcase |

### Reflections
- Cohort have a hard time choosing when they haven't worked directly with a PO. More knowledge sharing in Discovery and Analysis workshops would be helpful
- User stories might be helpful before wireframing. We could adapt the Analysis workshop to focus on mapping a user journey and writing user stories
- We might be able to fit in some element of pre-selection where the cohort can choose which PO's to work with in the Synthesis / PM workshops. I've done stuff like this in the past and I'm not always sure it works: losing buy-in on a Product early on means we won't have dev's to work with a particular PO.

**Comment by ByteSizedIT** [comment]
Linked to #783 - Create Tech for Better 1 pager in handbook

**Comment by Albadylic** [comment]
### Actions
- Adjust Discovery workshop timings so there's more time for each PO to share with the room
- Some more sharing in the research synthesis
- Add User Stories to Analysis workshop. Remove HMW and CS
