### ISSUE TITLE
New application project

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#781]
For each term, we update one of our application projects (see no. 2 on here: #715).

For Spring '23, I'd like to change out the comment box to something which makes more use of arrays.

**Comment by Albadylic** [comment]
Some ideas:
- Matching game
- Performing actions on a string (find shortest, sort alphabetically...) [this is pretty close to our code reads]
- ToDo list [this is in the testing topic]
- Tic tac toe
- A multi-step form [this is similar to the comment box]

**Comment by ivanmauricio** [comment]
Feature becomes game and people spend more time on it
Remove comment box, don't replace

for next time, take a look at dan's comment above
