### ISSUE TITLE
Team Code Review Format

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#784]
Suggestion from FAC25 SGC to alter composition of Team Code Review, so that 2 people from the project team being reviewed pair with 2 people from another team, enabling them to discuss/explain the project/code and overcome obstacles reviewing.

Taken as an action to discuss at Curriculum Circle

**Comment by ByteSizedIT** [comment]
Teams to do better documentation in ReadMe files.

@ivanmauricio  to do Intro's to Code Review session in week 1 and week 7.

@ByteSizedIT and @ivanmauricio to discuss scheduling.

**Comment by ivanmauricio** [comment]
@ivanmauricio and @ByteSizedIT to feed back on the effectiveness of this

**Comment by ivanmauricio** [comment]
going well so far but we'd like to run some experiments like:

- code review session being more flexible (could be q&A or even codealong)
- @ivanmauricio could do a live session with students on Mondays (alongside workshop discussions?)
