### ISSUE TITLE
Learning outcomes need to be made more specific

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#787]
The current pre-apprenticeship topic learning outcomes could be with more specific, some outcomes overlap and the number of outcomes varies a lot between topics.
- [Markup](https://github.com/foundersandcoders/coursebook/blob/main/src/course/syllabus/pre-apprenticeship/markup/learning-outcomes.md)
- [HTTP](https://github.com/foundersandcoders/coursebook/blob/main/src/course/syllabus/pre-apprenticeship/http/learning-outcomes.md)
- [Testing](https://github.com/foundersandcoders/coursebook/blob/main/src/course/syllabus/pre-apprenticeship/testing/learning-outcomes.md)

Now that we are using them as the basis for a portfolio and an end-of-course review, they need tightening up. We are planning to re-work them in time for FAC27.

**Comment by ivanmauricio** [comment]
@ivanmauricio and @ByteSizedIT to look at learning outcomes from full time programme learning outcomes
