### ISSUE TITLE
Project flow

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#791]
Some feedback from FAC24's final SGC:
- React and Next projects can feel a little disjointed
- There doesn't feel to be a need to build a project from scratch each week, and that sometimes the key learnings get missed in favour of getting a new project set up.
- The two final project timelines are quite short and it can be hard to get something valuable created within the two week build sprints

**Comment by ivanmauricio** [comment]
@Albadylic to survey fac25 on project experience

**Comment by Albadylic** [comment]
I'm gonna close this if I haven't done it by end of this sprint
