### ISSUE TITLE
Name game guidance

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#80]
This is a minor issue, but the last name game was a bit chaotic and too long. Could we ensure for Monday and record somewhere in the mentor notes that if alumni are going to join the circle they need to go after the students have all gone and it's ok for them to do it in pairs to speed things up a bit.

**Comment by oliverjam** [comment]
So that went a lot better. We should probably write it down before we forget.

That raises a good question: where do mentor notes go in the new curriculum? I guess there's nothing wrong with that doc living with the schedule and learning outcomes?

**Comment by Albadylic** [comment]
Yeah, I think there's space for the mentor notes next to schedule and LO's.

**Comment by jackherizsmith** [comment]
Perhaps to loop in with #182
