### ISSUE TITLE
Review support / guidance for windows users

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#814]
Some windows users have seemingly struggled a little more that other members of the cohort.

Potential steps to address this:

- [ ] Review setup of WSL with all windows ahead of full-time course. Current guidance is documented in the [System Requirements](https://learn.foundersandcoders.com/course/handbook/system-requirements/) section of the handbook.

- [ ] Confirm issue and potentially add guidance to curriculum (workshops and repos) for windows users when trying to run scripts*

- [x] Update curriculum to only advise creating node projects with `npm init -y`, rather than `echo "{}" > package.json`. 
For example, [Node & NPM](https://learn.foundersandcoders.com/workshops/node-npm-intro/#npm-init) workshop, [Http Servers with Node and Express](https://learn.foundersandcoders.com/learn/server/#getting-started)  workshop, [Persisting Data with SQLite & Node](https://learn.foundersandcoders.com/learn/database/#using-sq-lite) workshop

*It seems that users that do not have WSL installed need to prefix scripts setting env vars with SET keyword, and separate commands with &

**Comment by Albadylic** [comment]
Open issue for getting some spare laptops:
https://github.com/foundersandcoders/tasks/issues/195

**Comment by ivanmauricio** [comment]
I will schedule some time with @ByteSizedIT and make changes to the documentation

**Comment by ivanmauricio** [comment]
@Psydwinder to add a section to the handbook detailing windows gotchas

**Comment by Psydwinder** [comment]
This has been completed with PR #879
