### ISSUE TITLE
T4B project presentation and handover guidance documentation

### ISSUE THREAD

**Issue by bobbysebolao** [foundersandcoders/coursebook#82]
Just raising this issue so that the HackMD documentation for the T4B project presentations and handover is linked to from the course book repo.

- [T4B project presentation guidance HackMD](https://hackmd.io/9e9V6E08Rqm3rYsamCG1fg)
- [T4B project handover guidance HackMD](https://hackmd.io/PzszOLoLSZy9qccuz1R5Bg)

**Comment by oliverjam** [comment]
@Albadylic did this happen? I know we have T4B stuff in the coursebook, just wanted to make sure we can close this

**Comment by Albadylic** [comment]
Oops! Sorry to reply 28 days later 🧟 

There is now guidance in the coursebook, it could do with a second glance before FAC20 encounter it and if we're happy we can close this.
