### ISSUE TITLE
Mentor schedule

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#830]
There will only be 8 mentors available from FAC26. FAC26 have highlighted it being hard on the individual on the one occasion that there was only one mentor for them

**Comment by Albadylic** [comment]
9 mentors with Niete, we can ask 3 mentors to mentor twice.

Or divide all mentor days by no. of mentors:
- 3 days of mentoring in a week
- 6 weeks
- 2 mentors per day
= 36 slots / 9 people = 4 days each

**Comment by Albadylic** [comment]
- What do we want the mentors to do in the first three days?
- What is delivered by staff? in particular, 2 CFs and Dev-in-Res
- How does this overlap with the new plan for post-course learning for apprentices?

**Comment by sofer** [comment]
This fits into a wider question about the role of mentors and CFs and whether or not we should consider two CFs.

**Comment by Albadylic** [comment]
be careful not to lose the benefit to the mentor - extra learning

**Comment by Albadylic** [comment]
No mentors from previous cohort for last two weeks.

More experienced mentors for React and Next weeks.

Gregor to communicate to em[ployers

**Comment by Albadylic** [comment]
Awaiting draft schedule to send to employers

**Comment by ByteSizedIT** [comment]
Draft schedule of mentors has been communicated to FAC26 [here](https://discord.com/channels/781095715681992734/1060544675963998238/1090593191918575707), based on the preferences expressed [here](https://airtable.com/appKA4hcyDYWp46Mx/tblcWrv6jf9A3l6eF/viwa4Js6bFr4LtXSM?blocks=hide)

**Comment by ByteSizedIT** [comment]
Spoken to @Psydwinder who will contact and confirm with Laura and Karol re week 3 moving to Tues-Fri
