### ISSUE TITLE
Change the top-level labels in the navigation

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#832]
As follows:

- APPLICATION -> APPLICATION
- PRE-APPRENTICESHIP -> FOUNDATION
- APPRENTICESHIP -> DEVELOPER

**Comment by sofer** [comment]
and also the nav.
- /pre-apprenticeship -> /foundation
- /apprenticeship -> /developer

This is about bringing the coursebook language into line with the new language on the website and to get away from apprenticeships being front end centre in our messaging.

**Comment by Albadylic** [comment]
A change in name or a change in structure too?

e.g. we had a question from an applicant about something in the handbook. Most of the stuff there is only relevant to the FT programme. Is the coursebook structured in a logical way just now?
