### ISSUE TITLE
Fridays in person

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#853]
There is a serious move to ask people to come in on Fridays.

Final decision on this pending discussion with incoming CF.

see #755

**Comment by ByteSizedIT** [comment]
Consideration needs to be given to week 3, which includes a Bank Holiday - see separate issue #856 . 

One option would be to move Monday-Thursday to run Tuesday-Friday (Week 3 Friday is a Consolidation day as there are no workshops ahead of week 4)

**Comment by ivanmauricio** [comment]
@Psydwinder to see how cohort like remote Fridays and then to potentially experiment with in-person Fridays after gauging the cohort's preferences.
