### ISSUE TITLE
Confirm plan for May Bank Holiday

### ISSUE THREAD

**Issue by ByteSizedIT** [foundersandcoders/coursebook#856]
Confirm plans for Monday 29th May, which is a Bank Holiday.

This will be week 3 ([Authentication Week](http://localhost:8080/course/syllabus/developer/authentication/schedule/))

**Comment by ByteSizedIT** [comment]
One suggestion for managing this is to slide the week back a day, with the Monday to Thursday schedule in week 3 taking place Tuesday to Friday. 

This could be managed with the cohort as the Friday in Week 3 (Authentication) is a consolidation day, with no workshops to prepare for Week 4 (Server-side app).

However, the Friday would need facilitating by the CF.

Any changes would need to be arranged/communicated with the mentors for the week.

**Comment by Albadylic** [comment]
Yes, let's do it. I've let mentor's employer know.

Leaving next-circle to confirm this before term starts.

**Comment by ByteSizedIT** [comment]
Discussed with @Psydwinder, who is going to confirm with Laura and Karol (mentors) for that week.

Have also booked the classroom for the Tuesday and Friday to facilitate the shift

**Comment by ivanmauricio** [comment]
@Psydwinder to update schedule to reflect this

**Comment by Psydwinder** [comment]
This has been done with PR #870
