### ISSUE TITLE
Our own slides platform

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#86]
If we think linking to slides from the coursebook is a better approach than putting content into the gitbook (shame gitbook doesn't have slide mode), we might want to think about consolidating on a single tool for creating them.

**Comment by oliverjam** [comment]
I agree that it's confusing right now. I'm not a massive fan of the custom Reveal.js setup: copy/pasting a template and writing a bunch of HTML each time is harder than just writing Markdown on HackMD.

It looks like HackMD support teams, would it suffice to group everything together in there? Looks like we can only have 3 members on the free tier, which might be enough (Dan, CF, DinR)

https://hackmd.io/team/fac/

**Comment by macintoshhelper** [comment]
Might be worth looking into Gatsby, MDX and `mdx-deck`? Would be possible to generate a docs website and slides from the current GitBook compatible markdown file structure. https://primer.style is a nice example of a Gatsby documentation site. Would allow for using `react-live` or some other live JS/HTML code editors. I'm exploring generating slides, pdfs and documentation from markdown lately.

Slides could be written like this:

```md
# Welcome to The Presentation

Subtitle here

---

# Slide 2
```

**Comment by oliverjam** [comment]
I built https://fac-slides.netlify.app/ a while ago to use for general presentations I do for FAC. If the team could take a look and see if it needs any changes/polish before we start using it for everything. It's basically a simplified HackMD clone that doesn't use Reveal.js

**Comment by oliverjam** [comment]
We're now using [fac-slides](https://github.com/foundersandcoders-members/fac-slides) for all the curriculum intros plus the information evenings and various other slides. I think we'll keep iterating on it but it works well so far
