### ISSUE TITLE
Software Development Paradigms

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#872]
Our SD apprentices have all been asked in their project assessments about different Software Development paradigms, and to justify why they chose a certain one. It's one of the distinction criteria.

> Evaluates different software development approaches in order justifying the best alignment with a given paradigm. (for example, object oriented, event driven or procedural)

We could use including reference to these somewhere in our curriculum. e.g. as a topic in the Conversational Curriculum #867

**Comment by Psydwinder** [comment]
Find a place within the curriculum to talk about programming paradigms

**Comment by Albadylic** [comment]
add to presentation guidance in React week, DB week?

reevaluate where this has come up in the programme in the last two weeks
