### ISSUE TITLE
Remove "Portfolio" section from handbook

### ISSUE THREAD

**Issue by ivanmauricio** [foundersandcoders/coursebook#888]
Move any useful resources from there to the application platform

@Psydwinder to reach out to @S-adefe to figure out what copy she wants moved over to application platform

**Comment by Psydwinder** [comment]
Portfolio section has been removed from handbook. It is part of the TFB Branch.

Sarah has added in some copy and one extra section in the application process which you can see here:

https://www.notion.so/foundersandcoders/Requirements-e4e40f08148a414f8b8ccb2f354a9566?pvs=4

**Comment by ivanmauricio** [comment]
closed via #895
