### ISSUE TITLE
Issue management and estimation slides

### ISSUE THREAD

**Issue by octaviacogher** [foundersandcoders/coursebook#918]
- Change background to dyslexia friendly 
-  Review the content - can we add in any diagrams instead of words using dual coding principles? 
-  Can we add in some of the verbal explanations given in the session e.g. references to Fibonacci sequences? 
- Could there be some questioning introduced or a pair discussion task/activity to check for understanding and engage the learners? (ie rather than just listening to the slides) 
-

**Comment by camelPhonso** [comment]
The slides have been updated following our review of the changes during the last Weekly Learning Review.

Only the content has been updated while the dyslexia-friendly changes suggested for the website are under review

**Comment by camelPhonso** [comment]
The slides have been updated following our review of the changes during the last Weekly Learning Review.

Only the content has been updated while the dyslexia-friendly changes suggested for the website are under review
